README.md
Add a paragraph to the readme detailing the naming conventions required for makers.
=> add section on maker name conventions

README.md, autoload/neomake/makers/c.vim
This was really easy to do thanks to #36, just a 3 line change for the maker :)
=> Added clang maker for c

README.md, autoload/neomake/makers/c.vim, autoload/neomake/makers/python.vim, autoload/neomake/makers/sh.vim, autoload/neomake/makers/zsh.vim
It seemed like there weren't enough Python makers, so I thought I'd add a maker for flake8.
=> Add flake8 maker for python files

README.md, autoload/neomake/makers/tex.vim
I added `lacheck` and `chktex` makers for checking tex/latex files.
=> add some checkers for tex

autoload/neomake.vim
=> Fix make modified

autoload/neomake.vim, doc/neomake.txt
=> Add the neomake_list_height option.

autoload/neomake.vim, plugin/neomake.vim
Create new function and command to allow execution of arbitrary shell
commands by using `:NeomakeSh echo foo bar` the same way one would use
`! echo foo bar` or `:Dispatch echo foo bar`
The function can also be used by other plugins to make leveraging
jobcontrol easy
=> Create NeomakeSh to allow executing of shell commands

autoload/neomake.vim
=> When running a maker, stop the old job before starting the new one

autoload/neomake.vim, autoload/neomake/utils.vim, doc/neomake.txt
=> Remove make_modified feature

autoload/neomake.vim, autoload/neomake/utils.vim, doc/neomake.txt
=> Neomake not expanding %

autoload/neomake/signs.vim
=> Placing Neomake's signs on top doesn't always work

README.md, autoload/neomake.vim, autoload/neomake/signs.vim, autoload/neomake/statusline.vim, autoload/neomake/utils.vim
Fixes #48
I'm going to go ahead and open this PR. Looks like statusline integration is broken, so I'll fix that first before I merge.
=> Processing lint results (placing signs) takes a long time on large files

autoload/neomake/signs.vim
=> Get rid of problematic GetSigns function because we don't need it!

autoload/neomake/makers/ft/rst.vim
=> Add linters for reStructured Text

README.md, autoload/neomake/makers/ft/scala.vim
...run scalac as a syntax checker.
=> add scala checker

autoload/neomake/utils.vim
=> Add fish to supported shells

autoload/neomake/makers/ft/php.vim
This adds (very rudimentary) support for the [PHPMD](http://phpmd.org/) linter.
=> Makers: support for phpmd

autoload/neomake.vim, autoload/neomake/makers/ft/javascript.vim, autoload/neomake/makers/ft/jsx.vim, autoload/neomake/utils.vim
=> Handle multiple filetypes

autoload/neomake/makers/ft/d.vim
Just a small change to output(and parse) the column number.
=> add column support for D.

autoload/neomake.vim, autoload/neomake/signs.vim
Fixes #100. This is a work in progress, not completely tested yet. The first two commits here belong to the PR #107 but are necessary for this one (I will clean the git history once the status of #107 is decided).
=> Keep state between two subsequent neomake runs.

autoload/neomake/makers/ft/typescript.vim
=> Add typescript/tslint maker

autoload/neomake.vim
=> Add maker name in the displayed message.

autoload/neomake/makers/ft/less.vim
Use lessc built-in linter (http://lesscss.org/)
=> Add Less (CSS) syntax checker

autoload/neomake.vim, plugin/neomake.vim
I had a look around the code to find a way to retrieve all possible makers but am not sure if I found the bast way.  Maybe you can tell me if there is a better way.
=> Add completion to Neomake and NeomakeSh.

autoload/neomake.vim, doc/neomake.txt
=> Allow to change the working directory of a maker.

README.md, autoload/neomake/makers/ft/puppet.vim
Here are some makers to check the syntax of Puppet manifests.
=> Add puppet makers

README.md, autoload/neomake/makers/ft/scala.vim
This simply adds the scalastyle checker as an option.  It's working on my setup.
=> Add scalastyle checker

README.md, autoload/neomake/makers/ft/javascript.vim
Hello.
This pull request adds the [flow](http://flowtype.org/) type checker.
=> Added flow type checker

autoload/neomake/makers/ft/scala.vim
Current scala checker is broken. This will fix it :)
=> fixing unterminated if statements & scala improvements

README.md, autoload/neomake/makers/ft/java.vim
Use javac as a syntax checker for java code.
=> Add maker for java

autoload/neomake/makers/ft/nim.vim
Added basic support for nim programming language.
=> Support for nim

autoload/neomake/makers/ft/tex.vim
This adds support for rubber and rubber-info to compile and analyze latex documents.
=> Support for rubber latex compilation

autoload/neomake/signs.vim
Support for errorformat %I and %A.
=> Support for informational and message signs

README.md, autoload/neomake/makers/ft/ruby.vim
[Reek](https://github.com/troessner/reek) detects code smells in Ruby files. This PR adds support to integrate detections in neovim.
=> Reek maker for ruby files

autoload/neomake.vim
Fixes issue #153
As per https://github.com/neovim/neovim/issues/3555
=> Append captured lines from makers correctly

autoload/neomake/makers/ft/cs.vim
support for c# using mono's mcs compiler -- same functionality as syntastic
=> c# file type maker

autoload/neomake/makers/ft/css.vim
Parts taken from syntastic's css checker
=> csslint maker

autoload/neomake/makers/ft/d.vim
Dub(the D package manager) had a series of changes over the past few months, just adding a few fixes to keep it up to date/make use of the IDE-helper functions it added for spitting out dependencies. And it recognizes a few more compiler messages correctly.
I think everything looks OK, but I'm not too well versed in vimscript.
=> D: update to work with newest dub(package manager)

autoload/neomake/makers/ft/python.vim
Hi,
I pull request to add the pep257 support (docstring convention checker).
Best regards,
Asher256
=> new python checker: pep257

README.md, autoload/neomake/makers/ft/ruby.vim
Port of `jruby` syntax checker from Syntastic.
=> Add JRuby syntax checker

autoload/neomake/signs.vim, plugin/neomake.vim
This pull request defines default colors corresponding to the sign column background, thus the default colors will look more natural
=> Default signs background highlight

autoload/neomake.vim, doc/neomake.txt, plugin/neomake.vim
Implements exit callbacks as specified in #162 
Finishes what @critiqjo started.
Also adds documentation.
=> [RFC] Finish implementing exit callbacks

README.md, autoload/neomake/makers/ft/css.vim
Added [Stylelint](https://github.com/stylelint/stylelint) maker for listing CSS files.
=> Add Stylelint maker for CSS files

autoload/neomake/signs.vim
=> Use case-insensitive compare when placing signs

CHANGELOG.md, autoload/neomake/makers/ft/rust.vim
=> fixed rustc command line parameter for rust maker

README.md, autoload/neomake/makers/ft/markdown.vim
Added [markdownlint](https://github.com/mivok/markdownlint).
=> added mdl for markdown file types

autoload/neomake/makers/ft/javascript.vim
=> Flow: Use --old-errror-format option

doc/neomake.txt
=> Fix :helptags / documentation by removing duplicate tags.

README.md, autoload/neomake/makers/ft/c.vim
[checkpatch](https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl) is a perl script that checks compliance with the [Linux kernel coding style](https://github.com/torvalds/linux/blob/master/Documentation/CodingStyle) guidelines.
=> Add checkpatch maker for c

autoload/neomake/makers/ft/moon.vim
=> Add moonscript maker (linter)

autoload/neomake/makers/ft/ada.vim
I've been using this locally for some time now without much issue and
decided it might be worth adding in its current state and improving as
situations dictate in the future.
Resolves https://github.com/benekastah/neomake/issues/297
Thanks
=> Add initial support for Ada (GNAT)

autoload/neomake/makers/ft/elixir.vim
[Credo](https://github.com/rrrene/credo) is a static analysis tool for elixir code.
Thanks for an amazing plugin :+1:
=> Add credo maker for Elixir

autoload/neomake/makers/ft/tex.vim
Adds support for latexrun (https://github.com/aclements/latexrun)
=> Add a maker for latexrun

autoload/neomake/makers/ft/markdown.vim, autoload/neomake/makers/ft/text.vim
[proselint](https://github.com/amperser/proselint/)
=> added proselint for text and markdown filetypes

autoload/neomake.vim
This will open the correct location list, in case a buffer is opened in
multiple windows.
TEST CASE:
- split a buffer into two windows
- run ":Neomake" in the first window
- switch to the other window
Results should get displayed with the first window.
=> Handle window switching around "lwindow"

README.md, autoload/neomake/makers/ft/ruby.vim
=> Add ruby-lint support

autoload/neomake/makers/ft/java.vim
Fixes #375 for gradle projects
=> Fix path to classpath.gradle

autoload/neomake/makers/ft/vim.vim
Improve vint maker to detect error type.
=> Detect error type of vint

README.md, autoload/neomake/makers/ft/nix.vim
Check nix files using nix-instantiate. Based on the syntastic checker:
https://raw.githubusercontent.com/scrooloose/syntastic/master/syntax_checkers/nix/nix.vim
=> Add support for nix

autoload/neomake/makers/ft/sh.vim
Ref: https://github.com/neomake/neomake/pull/362/files#r63291301
/cc @paretje
=> sh: shellcheck: use "Note" entries as "info" directly

autoload/neomake/makers/ft/c.vim, autoload/neomake/makers/ft/cpp.vim, autoload/neomake/makers/ft/d.vim, autoload/neomake/makers/ft/python.vim, autoload/neomake/makers/ft/scala.vim, autoload/neomake/utils.vim
I'm not sure if not just using `executable()` was intentionally?!
Inspired by https://github.com/neomake/neomake/pull/398#discussion_r62559441.
=> Simplify/cleanup neomake#utils#Exists

autoload/neomake/makers/ft/python.vim
A new Python maker called vulture is added (https://bitbucket.org/jendrikseipp/vulture). Vulture finds unused classes, functions and variables in your code.
=> vulture: a new python maker added

README.md, autoload/neomake/makers/ft/python.vim
Vulture (a new Python maker) was merged here: https://github.com/neomake/neomake/pull/420 . Let's indicate it in the README file too.
=> vulture is supported, so add it to the README file

autoload/neomake.vim
Fixes https://github.com/neomake/neomake/issues/424.
=> Fix E706 with multiple filetypes

autoload/neomake/makers/ft/vim.vim
=> vim: vint: include policy_name in output message

autoload/neomake/makers/ft/java.vim
enable `g:neomake_java_javac_classpath`.
Fix #462
=> Fix javac classpath option

autoload/neomake/signs.vim, autoload/neomake/utils.vim, doc/neomake.txt, plugin/neomake.vim
Fixes https://github.com/neomake/neomake/issues/204
Supersedes https://github.com/neomake/neomake/pull/248
=> signs: use a default set for hltext setting

.gitignore, .travis.yml, Makefile, autoload/neomake.vim, tests/_setup.vader, tests/fixtures/errors.sh, tests/sh.vader, tests/vimrc
Fixes https://github.com/neomake/neomake/issues/408.
=> Add test suite based on Vader and fix Vim regression

autoload/neomake/signs.vim, autoload/neomake/utils.vim
Ref: https://github.com/neomake/neomake/issues/467
Ref: https://github.com/neomake/neomake/issues/468
=> Improve neomake#signs#DefineHighlights

autoload/neomake/makers/ft/css.vim
Fixes https://github.com/neomake/neomake/issues/389
=> Update Stylelint formatter

autoload/neomake.vim, tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/333.
=> Complete all available markers, not just the enabled ones

autoload/neomake.vim
Doing this later provides the hook access to the processed
location/quickfix list.
Followup to #463.
@bounceme
Does this still work for you?
=> Move/refactor NeomakeMakerFinished autocommand

autoload/neomake/makers/ft/java.vim
Thanks @mhinz! (https://github.com/mhinz/vim-grepper/commit/955d8932868f0e5d390d33d85cbb267e2637e19d#commitcomment-18064940)
=> Fix usage of has-patch, which is available only for 7.4.237+

autoload/neomake.vim
Ref: https://github.com/neomake/neomake/pull/411/files/a6a7d98#r69232739.
=> Do not call RegisterJobOutput on exit

autoload/neomake.vim, autoload/neomake/statusline.vim, doc/neomake.txt, tests/integration.vader
Followup to #480.
@bounceme still good?
The name/place was changed, and also how context is passed in.
=> NeomakeFinished autocmd

autoload/neomake/makers/ft/vim.vim
Fix https://github.com/neomake/neomake/issues/442
=> Use --no-color by default for vint

autoload/neomake/signs.vim
See [#495](https://github.com/neomake/neomake/pull/495) for discussion
=> changed info_sign and InfoSign() to match documentation

doc/neomake.txt
=> use only spaces in doc

autoload/neomake.vim, doc/neomake.txt, tests/_setup.vader, tests/integration.vader, tests/vimrc
Closes https://github.com/neomake/neomake/pull/501.
Ref: https://github.com/neomake/neomake/pull/494.
=> Fix/move NeomakeCountsChanged; fix neomake#Sh; improve tests

autoload/neomake/makers/ft/haskell.vim
1. only enable makers that are available
1. use Stack to run makers, when Stack is available
1. add a maker for Liquid Haskell
=> improve Haskell makers

autoload/neomake/makers/ft/c.vim
Heavily inspired by the syntastic clang-check support.
First time I've done any VimL scripting, so do point out anything that is iffy.
=> Add clang-check support

autoload/neomake/signs.vim, tests/signs.vader
Fixes https://github.com/neomake/neomake/issues/540.
=> Fix neomake#signs#DefineHighlights for non-existing goups

autoload/neomake/makers/ft/scss.vim
Fixes https://github.com/neomake/neomake/issues/546.
=> Fix scss maker: return proper maker names

autoload/neomake/makers/ft/elixir.vim
Ref: https://github.com/neomake/neomake/pull/536#issuecomment-239577422.
/cc @alxndr
=> Add %E/%W to neomake#makers#ft#elixir#elixir

autoload/neomake/makers/ft/elixir.vim
Closes https://github.com/neomake/neomake/pull/379.
=> makers: elixir: use --format=oneline instead of --one-line

tests/makers.vader
Ref: https://github.com/neomake/neomake/pull/555
=> Add test to source all filetype makers

README.md, autoload/neomake/makers/ft/javascript.vim
https://github.com/sindresorhus/xo
=> Add the JavaScript xo linter

README.md, autoload/neomake/makers/ft/cf3.vim
Confirmed it works using CFEngine 3.6.
=> Add support for CFEngine 3

README.md
=> README: update/move contributors section

.travis.yml, Makefile
Thanks @saaguero.
Ref: https://github.com/neomake/neomake/pull/575/commits/ba651e2ab#r77454132
=> Travis: fix vint-diff for multiple files; move others to Makefile

.github/ISSUE_TEMPLATE.md, .travis.yml, Makefile, autoload/neomake.vim, doc/neomake.txt, plugin/neomake.vim, tests/integration.vader
This is just a first shot, and should be mentioned in the docs / issue
template.
TODO:
=> Add :NeomakeInfo and GitHub issue template

autoload/neomake/makers/ft/sh.vim, tests/sh.vader
Fixes https://github.com/neomake/neomake/issues/602.
=> sh: shellcheck: do not pass --shell if there is a shebang

README.md, autoload/neomake/makers/ft/fortran.vim
Hi,
Added makers for fortran: gfortran (GNU) and ifort (Intel).
Used the errorformat from syntastic.
Thanks
P.S. My first pull request
=> Fortran makers

autoload/neomake.vim, tests/integration.vader
Ref: https://github.com/neomake/neomake/issues/620#issuecomment-248897665
=> NeomakeInfo: only display settings starting with neomake_

tests/_setup.vader, tests/integration.vader, tests/neomake.vader
Ref: https://github.com/neomake/neomake/pull/575#issuecomment-249033234
=> Fix tests: https://github.com/neomake/neomake/pull/575#issuecomment-249033234

tests/integration.vader
=> Add "Neomake with windo" test, for 07f3807

tests/utils.vader
Thanks to dkasak for reporting it in
https://github.com/neomake/neomake/commit/1ac37c1679f.
=> Fix neomake#utils#CompressWhitespace tests

autoload/neomake/makers/ft/haskell.vim, tests/ft_haskell.vader
=> Rebase #624

Makefile
Fixes https://github.com/neomake/neomake/issues/657.
=> Fix "make testnvim" on OS X

autoload/neomake.vim, autoload/neomake/utils.vim, doc/neomake.txt, tests/_setup.vader, tests/integration.vader, tests/neomake.vader, tests/utils.vader
Ref: https://github.com/neomake/neomake/issues/656.
=> Improve logging and add timestamps with neomake_verbose=3

autoload/neomake.vim, autoload/neomake/makers/cabal.vim, autoload/neomake/makers/ft/fish.vim, autoload/neomake/makers/ft/java.vim, autoload/neomake/makers/ft/perl.vim, doc/neomake.txt, plugin/neomake.vim, tests/integration.vader
Fixes https://github.com/neomake/neomake/issues/598.
=> Use buffer_output=1 by default

autoload/neomake/makers/ft/julia.vim
Added a Julia maker based on [Lint.jl](https://github.com/tonyhffong/Lint.jl)
=> Added Lint.jl maker for Julia.

.travis.yml, Dockerfile.tests, Makefile
Ref: https://github.com/neomake/neomake/pull/685#issuecomment-252442956.
=> Travis: run vimhelplint through docker_vimhelplint

.travis.yml, doc/neomake.txt
Fixes https://github.com/neomake/neomake/issues/600.
Rebased https://github.com/neomake/neomake/pull/685.
=> Fix vimhelplint violations

autoload/neomake.vim, autoload/neomake/utils.vim
Also set remove_invalid_entries=0 and errorformat=%+G to catch
everything.
=> neomake#utils#MakerFromCommand: just use &shell

Makefile, tests/vim/vimrc
Ref: https://github.com/neomake/neomake/pull/688#issuecomment-253045474
=> Fix tests: improve Makefile and use absolute paths for vimrc

autoload/neomake.vim, tests/neomake.vader
=> neomake#Sh: fix job_id for sync

.travis.yml, Dockerfile.tests, Makefile, README.md, autoload/neomake.vim, tests/integration.vader
This is WIP to require a specific Vim version, where async is fixed.
=> Remove Vim hack, adding vim8027

doc/neomake.txt
=> Fix markup: backticks instead of stars for emphasizing

autoload/neomake.vim, tests/integration.vader, tests/neomake.vader
Ref: https://github.com/neomake/neomake/issues/720#issuecomment-255242438
=> Remove "#" from log messages

autoload/neomake.vim
Ref: https://github.com/neomake/neomake/issues/720#issuecomment-255460114
=> neomake#DisplayInfo: use fenced blocks for :ver and :mess

autoload/neomake.vim
Ref: https://github.com/neomake/neomake/issues/720
=> Improve logging for Windows/Vim issues

autoload/neomake.vim, doc/neomake.txt, tests/integration.vader
Ref: https://github.com/neomake/neomake/issues/720#issuecomment-255521531
=> Handle "append_file" from settings

autoload/neomake/makers/ft/julia.vim
=> fixed quoting on message for missing Lint.jl

autoload/neomake/makers/ft/pandoc.vim
For the `vim-pandoc` plugin and anyone setting `ft=pandoc`.
=> add pandoc filetype

autoload/neomake.vim, autoload/neomake/statusline.vim, autoload/neomake/utils.vim, tests/integration.vader, tests/statusline.vader
This allows for adding commands for this later.
It also fixes a NeomakeCountsChanged signal/hook issue.
=> Refactor resetting counts

autoload/neomake/makers/ft/typescript.vim
Ref: https://github.com/neomake/neomake/issues/720#issuecomment-255521531
Closes https://github.com/neomake/neomake/pull/565.
Ref: https://github.com/neomake/neomake/pull/494.
=> typescript: improve tsc maker

autoload/neomake/makers/ft/mail.vim
Very similar to the [text](https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/text.vim) filetype maker, but for the mail filetype
=> Add proselint for mail filetype

doc/neomake.txt
As far as I see it, this note is obsolete.
=> [RFC] Doc: remove obsolete note

autoload/neomake.vim, autoload/neomake/utils.vim, tests/utils.vader
Fixes https://github.com/neomake/neomake/issues/761.
=> Fix neomake#utils#MakerIsAvailable with empty result from GetMaker

autoload/neomake/makers/ft/pandoc.vim
=> return markdown#markdownlint settings for pandoc#markdownlint

tests/lists.vader
Fixes https://github.com/neomake/neomake/pull/777#issuecomment-261231531.
=> tests: fix 'AddExprCallback with changed windows inbetween'

autoload/neomake/makers/ft/python.vim
This requires pylama 7.1.0 for the new "parsable" format, which was released on Sep 7th already, but I had to manually update it on Arch Linux.
However, often it is used in virtualenvs or with other methods like pipsi, so that should not really be a problem?!
=> python: improve pylama maker

autoload/neomake/makers/ft/vue.vim
Add makers for https://vuejs.org/ (`.vue` filetype).
=> makers: add vue ft

tests/utils.vader
Ref: https://github.com/neomake/neomake/pull/809#issuecomment-265277571
=> tests: more for neomake#utils#MakerIsAvailable

autoload/neomake.vim
This reverts a part of 4955a74, which seems to work now?!
=> neomake#CancelJob: revert unletting from s:jobs

autoload/neomake.vim, autoload/neomake/highlights.vim, autoload/neomake/signs.vim, plugin/neomake.vim, tests/include/setup.vader
/cc @davidosomething as per https://github.com/neomake/neomake/pull/497
=> Improve init/define for signs and highlights

autoload/neomake/makers/ft/python.vim
Seems the code is C901
```shell
[0:48]~/scratch/tools-hepdata[master]$ pylama -lmccabe wizard.py
wizard.py:11:1: C901 'ask_question' is too complex (13) [mccabe]
[0:49]~/scratch/tools-hepdata[master]$ pylama --version
pylama 7.3.1
```
=> Fixed McCabe code for Pylama

autoload/neomake.vim, tests/integration.vader
Ref: https://github.com/neomake/neomake/issues/864
=> Fix s:display_maker_info for FuncRef settings

autoload/neomake/highlights.vim, autoload/neomake/signs.vim, plugin/neomake.vim, tests/include/setup.vader
Fixes https://github.com/neomake/neomake/issues/864.
=> Fix init procedure: do sign/highlight setup in the autoload files

autoload/neomake/highlights.vim, doc/neomake.txt
=> Improve (column) highlighting

autoload/neomake/makers/ft/c.vim
=> C: treat notes as info messages instead of errors

autoload/neomake/makers/gradle.vim
Fixes #749 
And is the "over the weekend" pull request I promised :P
=> Add gradle maker

Makefile
Will come through https://github.com/junegunn/vader.vim/pull/103
=> Makefile: add testx command to abort on first error

autoload/neomake/makers/ft/markdown.vim, autoload/neomake/makers/ft/pandoc.vim, autoload/neomake/makers/ft/text.vim
Closes https://github.com/neomake/neomake/pull/773.
TODO:
https://github.com/btford/write-good/commit/a4e52ae33cff729e78e8f502a4ce37e7f7aa9887#commitcomment-19895355
=> Add writegood maker for text, markdown, pandoc

tests/neomake.vader
Ref: https://github.com/neomake/neomake/issues/897.
=> tests: improve "neomake#CancelJob with invalid job"

autoload/neomake/makers/ft/php.vim
Fixes https://github.com/neomake/neomake/issues/896
=> Update makers/ft/php.vim from Syntastic

autoload/neomake.vim, tests/include/setup.vader, tests/integration.vader, tests/processing.vader
Fixes https://github.com/neomake/neomake/issues/894.
=> Clean pending output in CleanJobinfo

autoload/neomake.vim, plugin/neomake.vim
`g:neomake_cursormoved_delay` is not documented on purpose for now.
Ref: https://github.com/neomake/neomake/issues/313
=> Handle CursorMoved delayed with timers

autoload/neomake/makers/ft/python.vim, tests/ft_python.vader
Fixes https://github.com/neomake/neomake/issues/925.
=> python: pylama: set entry.nr to fix mccabe handling

autoload/neomake.vim, autoload/neomake/makers/ft/python.vim, autoload/neomake/utils.vim, doc/neomake.txt, tests/args.vader, tests/errors.vader, tests/include/setup.vader, tests/integration.vader, tests/lists.vader, tests/mapexpr.vader, tests/neomake.vader, tests/processing.vader, tests/serialize.vader, tests/utils.vader
Ref: https://github.com/neomake/neomake/issues/577.
TODO:
=> [RFC] Fix serializing/chaining

autoload/neomake.vim, tests/completion.vader
=> neomake#GetMakers: look for makers in g:/b:

tests/ft_perl.vader, tests/neomake.vader
Ref: https://github.com/neomake/neomake/pull/937
=> tests: include ft_perl

tests/signs.vader
Fixes https://github.com/neomake/neomake/issues/943.
=> Add test for unplacing-signs

autoload/neomake/utils.vim, tests/utils.vader
Fixes https://github.com/neomake/neomake/issues/926.
=> Improve neomake#utils#ExpandArgs to handle %:r.o

autoload/neomake/utils.vim
Running Neomake after running Vader was giving me errors in the vader.vim repo.
=> Fix error when running neomake in vader files in another repo

Dockerfile.tests
Ref: https://github.com/neomake/neomake/pull/942#issuecomment-275246779
=> Docker images: use -py with vim73, and -py3 with vim-master

autoload/neomake.vim
Fixes https://github.com/neomake/neomake/issues/959
=> Fix quoting of argv for Vim on Windows

.gitignore
Kinda annoying when running tests locally.
=> Add tests/vim/plugins to .gitignore

autoload/neomake/makers/ft/javascript.vim, autoload/neomake/makers/ft/jsx.vim
neomake maker of https://github.com/bounceme/rjsx-compile
=> add rjsx-mode for jsx & js

autoload/neomake/makers/ft/javascript.vim
adds the `remove_invalid_entries` option and improves the elisp
=> rjsx improvements

autoload/neomake/makers/ft/nim.vim
Removed trailing whitespaces as well.
=> makers - nim: Use full file path

tests/hooks.vader, tests/include/setup.vader, tests/integration.vader, tests/lists.vader, tests/mapexpr.vader, tests/neomake.vader, tests/processing.vader, tests/serialize.vader
Ref: https://github.com/junegunn/vader.vim/pull/107#issuecomment-275887708
=> tests: use try-return-else-finish for new Vader

autoload/neomake/makers/ft/python.vim
Fixes https://github.com/neomake/neomake/issues/997.
=> python: mypy: use --fast-parser not with Windows

autoload/neomake.vim, tests/integration.vader
Fixes:  https://github.com/neomake/neomake/issues/516 and  https://github.com/neomake/neomake/issues/741.
=> Clear lists only after first output

README.md
=> Make logo text legible on dark background

autoload/neomake/makers/ft/python.vim, autoload/neomake/utils.vim, tests/utils.vader
Fixes #990
I skipped fixing one of the tests since I want to wait on a consensus on this.
=> Expand all % in arguments

autoload/neomake.vim, doc/neomake.txt, tests/hooks.vader
Fixes https://github.com/neomake/neomake/issues/1016.
=> Set exit_code on jobinfo for NeomakeJobFinished

autoload/neomake.vim, tests/integration.vader
Fixes https://github.com/neomake/neomake/issues/1013.
=> Fix exit_callback for neomake#Make/neomake#Sh

autoload/neomake.vim, autoload/neomake/highlights.vim, tests/include/setup.vader, tests/integration.vader
It needs to be done also after only successful makers finished.
Add also some tests for highlights.
=> Fix init_job_output

.github/ISSUE_TEMPLATE.md, autoload/neomake.vim, autoload/neomake/utils.vim, doc/neomake.txt, tests/include/setup.vader, tests/neomake.vader, tests/verbosity.vader
Fixes https://github.com/neomake/neomake/issues/510.
=> Add &verbose to g:neomake_verbose

autoload/neomake.vim, autoload/neomake/makers/ft/neomake_tests.vim, autoload/neomake/utils.vim, tests/integration.vader, tests/makers.vader, tests/neomake.vader, tests/serialize.vader, tests/utils.vader
Created based on https://github.com/neomake/neomake/pull/967.
TODO:
=> Improve handling of maker.exe

autoload/neomake.vim, autoload/neomake/makers/ft/lua.vim, autoload/neomake/makers/ft/python.vim, autoload/neomake/makers/ft/vim.vim, autoload/neomake/postprocess.vim, tests/ft_vim.vader, tests/neomake.vader, tests/postprocess.vader
=> Add generic postprocess to highlight named args

autoload/neomake/compat.vim, autoload/neomake/utils.vim, tests/json.vader, tests/neomake.vader
This is useful in general.
I plan to use it for a new redpen linter: https://github.com/redpen-cc/redpen
=> Add neomake#utils#JSONdecode

autoload/neomake/makers/ft/puppet.vim
Fixes https://github.com/neomake/neomake/issues/1069.
=> makers: puppetlint: fix args: escape percent sign

.travis.yml, Makefile, autoload/neomake.vim, tests/cwd-tcd.vader, tests/include/setup.vader, tests/makers.vader, tests/neomake.vader
Closes https://github.com/neomake/neomake/pull/1067.
=> Fix neomake#GetEnabledMakers for project makers

autoload/neomake.vim, tests/completion.vader, tests/neomake.vader
For some reason the `execute()` redir does not work anymore in Neovim during completions.
=> Fix completion for Neovim and improve it in general

autoload/neomake.vim, tests/integration.vader, tests/makers.vader, tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/1086.
=> Fix picking up project maker from g:neomake_enabled_makers

autoload/neomake/highlights.vim, tests/highlights.vader, tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/883.
=> Fix E803 with Vim highlights

autoload/neomake/utils.vim, tests/utils.vader
Ref: https://github.com/neomake/neomake/issues/1089
=> Expand tilde in neomake#utils#ExpandArgs()

autoload/neomake.vim, tests/verbosity.vader
Fixes: https://github.com/neomake/neomake/issues/1034
Ref: https://github.com/neomake/neomake/pull/976#issuecomment-284601321
=> Log when &verbose is used with makes

autoload/neomake.vim, doc/neomake.txt, tests/hooks.vader, tests/signs.vader, tests/tempfiles.vader, tests/utils.vader
Forgot this (TODO from https://github.com/neomake/neomake/pull/1057).
=> Disable tempfiles by default

autoload/neomake/makers/ft/python.vim
=> Python: Switch from pep8 to pycodestyle

autoload/neomake.vim, tests/filetypes.vader, tests/neomake.vader
Fixes https://github.com/neomake/neomake/pull/1114#issuecomment-287195679.
=> Fix getting enabled makers with multiple filetypes

autoload/neomake/makers/ft/asciidoc.vim, tests/ft_asciidoc.vader, tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/1128.
=> asciidoc: add support for asciidoc/asciidoctor

autoload/neomake.vim, doc/neomake.txt, tests/hooks.vader, tests/integration.vader, tests/processing.vader
Fixes https://github.com/neomake/neomake/issues/767.
=> Pass `jobinfo` to hooks

autoload/neomake/makers/ft/java.vim
Fixes https://github.com/neomake/neomake/issues/1139.
=> Fix java: do not set g:neomake_java_javac_maker

autoload/neomake.vim, autoload/neomake/makers/ft/idris.vim, tests/ft_idris.vader, tests/integration.vader, tests/lists.vader, tests/makers.vader, tests/processing.vader
To catch https://github.com/neomake/neomake/issues/1141 et al.
=> Add test to instantiate all makers

autoload/neomake.vim, doc/neomake.txt, tests/makers.vader
Fixes https://github.com/neomake/neomake/pull/1123#issuecomment-288536452.
=> s:ProcessEntries: use bufnr from entries if present

autoload/neomake/compat.vim, tests/compat.vader, tests/include/setup.vader, tests/neomake.vader
Currently only used in tests, but will be used with automaking, too.
=> Add neomake#compat#uniq

autoload/neomake/makers/ft/elm.vim
`context.output` returns each line from the output and the
`elm-make` output groups warnings in a JSON array on one line and
errors on the next line in a separate JSON array. This commit
iterates over the `context.output` so that we're actually showing
the errors instead of just warnings if both exist.
=> Improve error displaying for elm-make maker

autoload/neomake.vim, tests/processing.vader
Fixes https://github.com/neomake/neomake/issues/1158.
=> Fix restarting of finished jobs

autoload/neomake/makers/ft/javascript.vim
This turned out to be feasible a while ago.
No tests, sorry.
=> javascript: jshint: use GenericLengthPostprocess

doc/neomake.txt, tests/postprocess.vader
Ref: https://github.com/neomake/neomake/issues/1164#issuecomment-290220133
=> doc: postprocess: add lambda example (with tests)

autoload/neomake.vim, tests/tempfiles.vader
Uses binary mode with writefile.
=> tempfiles: do not append empty line

Makefile
TODO
Via https://github.com/junegunn/vader.vim/pull/107.
=> Use my friendly Vader fork

autoload/neomake.vim, doc/neomake.txt, tests/makers.vader
=> Add support for neomake#Make accepting a dict directly

autoload/neomake/makers/ft/rust.vim
See this test: https://github.com/neomake/neomake/blob/master/tests/ft_rust.vader#L8
=> Rust: Remove TODO for necessary check

autoload/neomake.vim, tests/include/setup.vader, tests/processing.vader, tests/tempfiles.vader, tests/utils.vader
This simplifies it and makes it more useful in tests.
=> Move already-running check, improve MakerFromCommand tests

autoload/neomake.vim, tests/include/setup.vader, tests/tempfiles.vader, tests/utils.vader
=> Store tempfiles on make_info

autoload/neomake/makers/ft/chef.vim
Following up on https://github.com/neomake/neomake/pull/585.
Closes https://github.com/neomake/neomake/pull/585.
=> Add chef filetype support (ruby + foodcritic)

autoload/neomake.vim, tests/env.vader, tests/neomake.vader
Via https://github.com/neomake/neomake/pull/1192#issuecomment-292817190.
=> Provide NEOMAKE_FILE in env

autoload/neomake/makers/ft/go.vim
Go has a quite a number of static analysis tools outside of the standard compiler, lint and vet checks.
Gometalinter help manage (install and update) and standardise the output of the checks to a single format.
I've added gometalinter support because a user can then use this intermediate tool to enable or disable various checkers/linters themselves without having to further customise neomake.
WIP:
- ~I'd like users to be able to adjust the `args` as they see fit, the ones I've proposed show few false positives and usually refer to issues that really do need to be fixed (or have left dead code around and can be safely removed).~ Fixed in ad531ac7473a732b8a7c39b3e02e2e8b88b026ab
- ~Can users disable the gometalinter if they do not want to use it, even though it is installed?~ Yes they can …
=> Go: add gometalinter

autoload/neomake.vim
Noticed with https://github.com/neomake/neomake/pull/1225.
=> Fix s:AddExprCallback for changed lists inbetween

autoload/neomake.vim, tests/postprocess.vader
Fixes https://github.com/neomake/neomake/issues/1230.
=> Fix removal of multiple entries in s:AddExprCallback

.travis.yml, Dockerfile.tests, Makefile
Requires / build upon https://github.com/tweekmonster/vim-testbed/pull/9.
=> WIP: Add Neovim to Docker targets

autoload/neomake/makers/ft/go.vim
Pretty sure that's not a thing, at least it's not for me.
=> Removing g:let as I'm pretty sure it's a typo

autoload/neomake/makers/ft/go.vim
Some suggestions based on comments in https://github.com/neomake/neomake/pull/795.
=> Go: serialize / prefer gometalinter

autoload/neomake/makers/ft/tex.vim
Ref: https://github.com/neomake/neomake/pull/1236#issuecomment-297984204
=> pdf: do not enable pdflatex by default

autoload/neomake/makers/ft/javascript.vim, tests/ft_javascript.vader, tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/1238.
=> javascript: eslint: ignore "X problem(s)" footer

autoload/neomake.vim, tests/include/setup.vader, tests/processing.vader
This also adds NeomakeTestsWaitForMessage.
=> ProcessJobOutput: try/catch errors

autoload/neomake/makers/ft/haskell.vim
Ref: https://github.com/neomake/neomake/pull/1263#discussion_r114088324
=> haskell: hdevtools: fix usage of empty

tests/include/setup.vader, tests/integration.vader, tests/utils.vader
Simulate real shellcheck by mocking it always.
=> tests: mock shellcheck, rename NeomakeTests{Ensure,Create}Exe

autoload/neomake/makers/ft/purescript.vim, tests/ft_purescript.vader, tests/neomake.vader
Instead of #359 this is a simpler PureScript maker based on the Elm maker. This is pretty barebones at the moment but I'd love any and all feedback!
=> Add purescript maker

autoload/neomake.vim, tests/tempfiles.vader, tests/utils.vader
Ref: https://github.com/neomake/neomake/issues/1212
TODO:
=> tempfiles: use a list and keep track of created dirs

autoload/neomake.vim, tests/lists.vader, tests/makers.vader, tests/processing.vader
TODO:
- ~~[ ] refactor it into a `neomake#lists` module?! (mostly relevant if you do not use the list feature; but the queue will probably be used for other things later, too)~~
=> Improve loclist/qflist handling with queued :lwindow

autoload/neomake/makers/ft/vue.vim
@jacoborus 
Please verify that this still works.
This way you get the benefits of https://github.com/neomake/neomake/pull/1250 etc.
=> vue: extend upstream (javascript) makers

autoload/neomake/config.vim, autoload/neomake/utils.vim, tests/config.vader, tests/utils.vader
=> Improve dict config

autoload/neomake/makers/ft/c.vim, autoload/neomake/makers/ft/cpp.vim
See http://cppcheck.sourceforge.net/.
=> Add cppcheck c/cpp maker

autoload/neomake/makers/ft/javascript.vim, autoload/neomake/makers/ft/jsx.vim, tests/filetypes.vader
Followup of https://github.com/neomake/neomake/pull/1394.
=> javascript/jsx: add stylelint (via Styled Components)

autoload/neomake.vim, doc/neomake.txt, tests/hooks.vader
Fixes https://github.com/neomake/neomake/issues/1271.
TODO:
=> Add NeomakeJobStarted/NeomakeJobInit hooks, allowing to set niceness

tests/lists.vader
Some of them were accidentally disabled in 604ddb5d.
=> tests: lists: re-enable tests

tests/include/setup.vader
=> tests: fix cache busting with fixed Vim

plugin/neomake.vim
Ref: https://github.com/dojoteef/neomake-autolint/issues/21.
=> Toggle commands: display status always

autoload/neomake/makers/ft/serpent.vim
A maker for the `serplint` [Serpent](https://github.com/ethereum/serpent) linter.
Here it is in action:
=> Add Serpent maker

Makefile, autoload/neomake/highlights.vim, autoload/neomake/signs.vim, autoload/neomake/utils.vim, plugin/neomake.vim, tests/highlights.vader, tests/signs.vader, tests/vim/vimrc
Fixes https://github.com/neomake/neomake/issues/922.
=> (Re)define signs/highlight on ColorScheme

autoload/neomake/highlights.vim, autoload/neomake/signs.vim, plugin/neomake.vim, tests/include/init.vim
Let's be more lazy.
Fixes https://github.com/neomake/neomake/issues/1448.
=> Do not use VimEnter for defining highlights

contrib/vim-checks, plugin/neomake.vim
Also fixes the style validations in plugin/neomake.vim.
=> Fix contrib/vim-checks for single files in dir

autoload/neomake.vim, tests/integration.vader
To be used for debugging/logging.
=> Add jobinfo.as_string

autoload/neomake/makers/sbt.vim, tests/completion.vader
[sbt](https://github.com/sbt/sbt) is the "simple build tool" for Scala, Java, etc.
This fixes #1472.
=> Add directory maker for sbt

autoload/neomake/compat.vim, tests/compat.vader
Closes https://github.com/neomake/neomake/pull/1490.
=> win: vim: fix double-wrapping args in shell

autoload/neomake/makers/ft/javascript.vim, tests/ft_javascript.vader
Fixes https://github.com/neomake/neomake/issues/1506.
=> js: standard: filter out verbose messages

autoload/neomake/makers/ft/javascript.vim
Fixes https://github.com/neomake/neomake/issues/1473.
=> javascript: flow: handle new errorformat

autoload/neomake/highlights.vim, autoload/neomake/signs.vim, autoload/neomake/utils.vim, tests/signs.vader, tests/utils.vader
Refactored neomake#signs#HlexistsAndIsNotCleared into it, adding
neomake#utils#parse_highlight.
=> Add neomake#utils#highlight_is_defined

autoload/neomake.vim, doc/neomake.txt, tests/cancellation.vader, tests/cwd.vader, tests/hooks.vader, tests/include/init.vim, tests/integration.vader, tests/lists.vader, tests/processing.vader
=> Improve action queue handling, including E48/E523

autoload/neomake.vim, tests/processing.vader, tests/serialize.vader
Fixes https://github.com/neomake/neomake/issues/1536.
=> Cancel previous jobs at the start of Make

autoload/neomake/makers/ft/typescript.vim
=> fix: add pretty false to tsc option

autoload/neomake.vim, tests/makers.vader
=> tests: harden/improve "pcall aborts after 3 attempts per job"

.travis.yml, Makefile, autoload/neomake/utils.vim
Exit code 1 means failure, while any other indicates errors.
=> Travis: exit with code 1 when `make` fails

.travis.yml, Makefile
=> Travis: fix install step for travis_lint

autoload/neomake.vim
Closes https://github.com/neomake/neomake/pull/1567.
=> s:clean_make_info: assert that there are no queued jobs/makes

autoload/neomake.vim, autoload/neomake/makers/ft/neomake_tests.vim, autoload/neomake/utils.vim, tests/compat.vader, tests/completion.vader, tests/errors.vader, tests/makers.vader
=> File project mode cleanup

.travis.yml, Dockerfile.tests, Makefile
Includes profiling support for older Vims (via --with-features=huge).
=> Bump Docker image

.coveragerc, .travis.yml, Makefile, tests/vim/vimrc
Based on https://github.com/Vimjas/covimerage.
=> Coverage reporting

autoload/neomake/statusline.vim, tests/processing.vader
Fixes https://github.com/neomake/neomake/issues/1621.
=> statusline: use redrawstatus

Makefile, autoload/neomake.vim, tests/isolated.vader, tests/isolated/tempfiles-cleanup.vader
Ref: https://github.com/neomake/neomake/issues/1617
=> Improve cleanup of temporary files

autoload/neomake/config.vim, autoload/neomake/utils.vim, tests/config.vader, tests/utils.vader
Ref: https://github.com/neovim/neovim/issues/7432#issuecomment-338513967
=> GetSetting/config#get: do not return partials

autoload/neomake/utils.vim, tests/utils.vader
Ref: https://github.com/neovim/neovim/issues/7432
=> neomake#utils#fix_self_ref: test/workaround for o.func = o.func

Makefile, contrib/vim-checks, tests/compat.vader, tests/hooks.vader, tests/include/init.vim, tests/serialize.vader, tests/utils.vader
This helps NixOS, and is good practice anyway.
Ref: https://github.com/neomake/neomake/issues/1594
=> Use SHELL='/usr/bin/env bash'

autoload/neomake/statusline.vim, doc/neomake.txt, tests/statusline.vader
Ref: https://github.com/vim-airline/vim-airline/issues/1567#issuecomment-336712410
=> doc: statusline: format_status

autoload/neomake/makers/ft/ruby.vim
=> Add some sensible defaults to rubocop arguments

autoload/neomake.vim
Ref: https://github.com/neomake/neomake/issues/1705
=> Hotfix for error with empty lists

autoload/neomake/utils.vim, tests/hooks-queue.vader, tests/main.vader
Fixes https://github.com/neomake/neomake/issues/1587.
=> hooks / User autocmds: use stack of context global

doc/neomake.txt
=> just doc b:neomake_enabled_makers

autoload/neomake.vim, tests/integration.vader
Might help with debugging https://github.com/neomake/neomake/issues/1730#issuecomment-344985165.
=> create_locqf_list: pass in jobinfo for log context

autoload/neomake/statusline.vim, doc/neomake.txt, tests/statusline.vader
=> varname in code -- format_ok -> format_loclist_ok

autoload/neomake.vim, tests/integration.vader, tests/makers.vader
This allows for configuring e.g. `pty=1` for makers.
Helps with https://github.com/neomake/neomake/issues/1704.
=> Add nvim_job_opts/vim_job_opts maker settings

autoload/neomake/makers/ft/css.vim, tests/ft_css.vader
Fixes https://github.com/neomake/neomake/issues/1654.
=> stylelint: fix errorformat and add postprocessing

autoload/neomake.vim
=> Use $NEOMAKE_DO_COVERAGE for coverage hack

plugin/neomake.vim, tests/toggle.vader
=> Improve disabling

autoload/neomake/makers/ft/java.vim
* Ignore status messages
* Ignore _JAVA_OPTIONS
* Parse errors without a column number
=> improve checkstyle error format

autoload/neomake/makers/ft/css.vim, tests/ft_css.vader
Ref: https://github.com/SpaceVim/SpaceVim/issues/1159
=> stylelint: handle error msg from missing config

autoload/neomake.vim
This might potentially save us some autocommand(s).
=> s:handle_locqf_list_for_finished_jobs: close before emptying

autoload/neomake/makers/ft/javascript.vim, doc/neomake.txt
Fix an issue eslint_d invokes global ESLint for local project files.
=> Fix an eslint_d issue

autoload/neomake.vim
Taken out of https://github.com/neomake/neomake/pull/1837.
=> autoload/neomake.vim: add s:is_testing

autoload/neomake.vim
Ref: https://github.com/neovim/neovim/issues/7913
=> Move substitution of \r to s:output_handler

autoload/neomake.vim
Ref: https://github.com/neovim/neovim/issues/8083#issuecomment-369415751
=> nvim: short-circuit EOF with 0.2.0+

autoload/neomake.vim
Ref: https://github.com/vim/vim/issues/2350
=> Re-add hack for keeping references when profiling with neomake#GetMaker

autoload/neomake/compat.vim, tests/isolated/compat-get_argv-on-emulated-windows.vader
Fixes https://github.com/neomake/neomake/issues/1893
=> Fix args handling with Windows

tests/isolated/compat-get_argv-on-emulated-windows.vader, tests/isolated/highlights.vader, tests/isolated/modes.vader, tests/isolated/tempfiles-cleanup.vader, tests/isolated/utils-DebugMessage-handles-missing-make-options.vader
=> tests: isolated: restore if not run separately

autoload/neomake/makers/ft/python.vim, tests/ft_python.vader
Fixes https://github.com/neomake/neomake/issues/1828.
=> python: pylint: filter Python warnings

autoload/neomake/statusline.vim, doc/neomake.txt, tests/statusline.vader
This is something that can solve #1861
This is a breaking change, it might be useful to review this with extra
care.
=> Improve statusline customization

autoload/neomake/configure.vim, tests/automake.vader
Ref: https://github.com/neomake/neomake/issues/1901
=> automake: revisit timer handling/stopping

autoload/neomake/makers/ft/javascript.vim
=> eslint: support stdin

autoload/neomake/makers/ft/sh.vim
This is meant to improve it further with dict functions later.
=> sh: shellcheck: use singleton by default

autoload/neomake.vim
This can be used for fixers later.
=> Factor out neomake#get_nearest_error

autoload/neomake/makers/ft/javascript.vim, tests/ft_javascript.vader
Fixes https://github.com/neomake/neomake/issues/1966.
=> javascript: flow: do not include trailing newlines in errors

autoload/neomake.vim, tests/lists.vader
Fixes https://github.com/neomake/neomake/issues/1970.
=> lists: resize existing qf windows with following jobs

autoload/neomake.vim, autoload/neomake/utils.vim, tests/cwd.vader, tests/ft_xml.vader, tests/stdin.vader, tests/tempfiles.vader, tests/utils.vader
Ref: https://github.com/neomake/neomake/issues/1029#issuecomment-401839438
=> Improve tempfile handling with regard to cwd

autoload/neomake/makers/ft/python.vim, tests/ft_python.vader
Fixes https://github.com/neomake/neomake/issues/1990.
=> python: filter FutureWarnings

autoload/neomake/makers/ft/dockerfile.vim
=> Dockerfile: Add support for hadolint linting

autoload/neomake/makers/ft/ruby.vim
=> add flog to ruby

autoload/neomake/makers/ft/ansible.vim
=> add yamllint to ansible

autoload/neomake/makers/ft/kotlin.vim
fix #1984
doesn't really need a test...
=> add ktlint maker

autoload/neomake/makers/ft/r.vim
=> add r lint

autoload/neomake/makers/ft/haxe.vim
=> add haxe lint

autoload/neomake.vim, tests/isolated.vader, tests/isolated/resets-ignore_automake_events.vader
TODO:
IIRC I've seen this not being decremented due to an error inbetween, and then Neomake would skip BufWritePost due to it.
=> Decrement s:ignore_automake_events always

.circleci/config.yml, Dockerfile.tests, Makefile
Ref: https://github.com/vim/vim/pull/2499
=> Docker: use fixed-profiling patch with vim81

autoload/neomake.vim, tests/lists.vader
Ref: https://github.com/neomake/neomake/issues/2032
=> Improve logging with resizing of list window

doc/neomake.txt, tests/makers.vader
Fixes https://github.com/neomake/neomake/issues/2039
=> Fix doc for global remove_invalid_entries

autoload/neomake.vim, autoload/neomake/config.vim, autoload/neomake/debug.vim, tests/makers.vader
Fixes https://github.com/neomake/neomake/issues/2039#issuecomment-410526627
=> Initialize maker_defaults setting

autoload/neomake.vim, tests/lists.vader
Fixes https://github.com/neomake/neomake/issues/2037.
=> tests: cover closing of list window via :lwindow

autoload/neomake/cmd.vim, tests/isolated.vader, tests/isolated/completion-handles-throw.vader
Fixes https://github.com/neomake/neomake/issues/2045.
=> completion: handle errors from maker functions

autoload/neomake/makers/ft/crystal.vim
An [Ameba](https://veelenga.github.io/ameba/) linter for [Crystal](https://crystal-lang.org/).
=> Crystal Ameba linter

autoload/neomake.vim, tests/errors.vader, tests/include/init.vim, tests/integration.vader
=> Fix `:Neomake! maker`

tests/integration.vader
Flaky on vim80 (https://circleci.com/gh/neomake/neomake/14346).
=> tests: harden "Location list should be cleared only after first output"

autoload/neomake.vim
It might return "not processed".
=> s:clean_make_info: return s:handle_locqf_list_for_finished_jobs

autoload/neomake/highlights.vim, doc/neomake.txt, tests/highlights.vader
Ref: https://github.com/neomake/neomake/pull/2113#discussion_r228731510
=> Allow to highlight both columns (if present) and lines

autoload/neomake.vim, autoload/neomake/action_queue.vim, autoload/neomake/jobinfo.vim, autoload/neomake/utils.vim, tests/action_queue.vader, tests/cwd.vader, tests/ft_go.vader, tests/hooks-queue.vader, tests/include/init.vim, tests/integration.vader, tests/isolated/modes.vader, tests/lists.vader, tests/main.vader, tests/makers.vader, tests/processing.vader, tests/tempfiles.vader
Ref/via: https://github.com/neomake/neomake/issues/2114#issuecomment-433712681
=> Fix handling of pending output (order, exit)

autoload/neomake/makers/ft/markdown.vim
alex supports `--stdin` in v `6.0.0`
=> [feat] add stdin support to alex maker

autoload/neomake.vim, autoload/neomake/compat.vim, autoload/neomake/utils.vim, tests/cancellation.vader, tests/lists.vader, tests/signs.vader
=> Postpone QuickfixCmdPost autocommand (after signs being placed)

autoload/neomake/quickfix.vim, autoload/neomake/signs.vim, tests/customqf.vader, tests/signs.vader
Taken out of https://github.com/neomake/neomake/pull/2124.
=> custom qf: unplace signs with non-Neomake list

tests/action_queue.vader, tests/include/init.vim
Example failure: https://circleci.com/gh/neomake/neomake/15765
=> tests: harden flaky test and action queue cleanup

autoload/neomake.vim, autoload/neomake/cmd.vim, autoload/neomake/highlights.vim, autoload/neomake/quickfix.vim, doc/neomake.txt, plugin/neomake.vim, tests/clean.vader, tests/integration.vader, tests/main.vader, tests/signs.vader
=> Add commands for cleaning

autoload/neomake.vim, tests/lists.vader
Ref: https://github.com/neomake/neomake/issues/2148
=> Use :silent with delayed execution of '#QuickfixCmdPost'

autoload/neomake.vim, autoload/neomake/statusline.vim, contrib/highlight-log, doc/neomake.txt, tests/isolated/statusline-highlights.vader, tests/statusline.vader
Display running jobs for the different location list and quickfix list
sections.
=> statusline: running jobs per file/project mode

autoload/neomake/utils.vim, tests/utils.vader
Fixes https://github.com/neomake/neomake/issues/2156.
=> ExpandArgs: handle %<

autoload/neomake.vim, doc/neomake.txt, tests/lists.vader
Ref https://github.com/neomake/neomake/pull/1064.
=> open_list/list_height can be set with normal settings

autoload/neomake/compat.vim, tests/compat.vader
Taken out of https://github.com/neomake/neomake/pull/2023.
=> Add neomake#compat#buf_{get,set}_lines

autoload/neomake.vim, autoload/neomake/virtualtext.vim, doc/neomake.txt, plugin/neomake.vim
=> virtualtext support

autoload/neomake/configure.vim, tests/automake.vader
Ref: https://github.com/neomake/neomake/issues/2175
=> Improve logging with automake cancellation: include event

autoload/neomake.vim, autoload/neomake/configure.vim, tests/automake.vader
Fixes https://github.com/neomake/neomake/issues/2175.
=> Restart make when buffer changed, instead of canceling

autoload/neomake/configure.vim, tests/automake.vader
Ref: https://github.com/neomake/neomake/issues/2175
=> automake: fix/improve restarting

tests/automake.vader
Build failure: https://circleci.com/gh/neomake/neomake/17967
=> tests: fix flaky automake test

autoload/neomake.vim, autoload/neomake/list.vim, autoload/neomake/quickfix.vim, tests/automake.vader, tests/customqf.vader, tests/include/init.vim, tests/include/setup.vader, tests/list.vader, tests/lists.vader, tests/serialize.vader, tests/utils.vader
This moves it from being set via customqf only.
TODO:
=> list: set title

autoload/neomake/configure.vim, tests/automake.vader
Ref: https://github.com/neomake/neomake/issues/2175
=> automake: restart always, issue a warning when no delay

autoload/neomake.vim, tests/include/init.vim, tests/isolated/resets-ignore_automake_events.vader, tests/list.vader, tests/lists.vader
Fixes https://github.com/neomake/neomake/issues/2241.
=> Look at quickfix list for reusing list with file_mode=0

autoload/neomake/configure.vim, tests/automake.vader
Fixes https://github.com/neomake/neomake/issues/2175.
=> Use another workaround for Vim issue 2742

autoload/neomake/configure.vim, tests/automake.vader
Ref: https://github.com/neomake/neomake/issues/2175#issuecomment-450144893.
=> Fix TextChanged workaround once more

autoload/neomake/list.vim
(I am mocking the Assert command myself using echo, and this caused
redraw issues in Neovim)
=> list: use Vader functions for assertions

autoload/neomake.vim, autoload/neomake/action_queue.vim, tests/action_queue.vader
=> action queue: handle queued make info correctly

autoload/neomake/makers/ft/beancount.vim
=> Add beancount maker

.circleci/config.yml, Dockerfile.tests, Makefile
https://github.com/Vimjas/covimerage/releases/tag/v0.1.3
=> Docker: update covimerage to 0.1.4

autoload/neomake/makers/ft/typescript.vim, tests/ft_typescript.vader
Fixes https://github.com/neomake/neomake/pull/2307.
=> typescript: tslint: specify formatter, handle warnings

autoload/neomake.vim, autoload/neomake/utils.vim, doc/neomake.txt, tests/tempfiles.vader
Fixes https://github.com/neomake/neomake/issues/1736.
=> Add setting for custom tempfile directory

autoload/neomake/makers/ft/go.vim, tests/ft_go.vader
=> add golangci-lint maker

autoload/neomake/makers/ft/swift.vim
Fixes https://github.com/neomake/neomake/issues/2342.
=> swift: swiftpm: set cwd based on Package.swift

autoload/neomake/signs.vim, autoload/neomake/utils.vim, autoload/neomake/virtualtext.vim
1. Factor out neomake#utils#define_derived_highlight
2. improve default highlight groups
=> [WIP] virtualtext improvements

tests/include/setup.vader, tests/vim/vimrc
This is relevant for when using a file from a subdirectory ("isolated").
=> tests: minor fixes/cleanup

autoload/neomake.vim, autoload/neomake/action_queue.vim, autoload/neomake/compat.vim, autoload/neomake/core.vim, tests/action_queue.vader, tests/compat.vader, tests/processing.vader
This reverts commit 1686a91cc4ea4b48152e314decb827946221b1ad.
=> Do not use noautocmd when restoring windows

autoload/neomake/cmd.vim, tests/toggle.vader
Fixes https://github.com/neomake/neomake/issues/2372.
=> Fix NeomakeBufferEnable directly after NeomakeDisable

tests/toggle.vader
Accidentally disabled/ignored in 7c93f8443.
=> tests/toggle.vader: re-enable tests

autoload/neomake/makers/ft/lua.vim
=> lua: luacheck: do not add length (highlight) with W631

autoload/neomake/makers/ft/rust.vim
Closes https://github.com/neomake/neomake/issues/2398.
=> rust: cargo: set tempfile_enabled=0

autoload/neomake.vim, autoload/neomake/core.vim, tests/stdin.vader
Ref: https://github.com/neomake/neomake/issues/2411#issuecomment-520171033
=> Handle uses_stdin with append_file=0 and without uses_filename

autoload/neomake/makers/ft/python.vim
=> python: mypy: use type=I for "Need type annotation/comment for"

autoload/neomake/makers/ft/python.vim, doc/neomake.txt, tests/ft_python.vader, tests/makers.vader
Adds tests/doc for not using copy with InitForJob.
=> python: mypy: fix InitForJob

.circleci/config.yml, Dockerfile.tests, Makefile, tests/automake.vader, tests/vim_and_neovim_behavior.vader
Expected to fail for vim-master with covimerage.
=> tests: bump Docker image

autoload/neomake/utils.vim, tests/utils.vader
Ref: https://github.com/neovim/neovim/issues/7432
=> Fix/improve neomake#utils#fix_self_ref for Neovim (use get())

autoload/neomake/list.vim, tests/list.vader
Ref: https://github.com/neomake/neomake/pull/2461
=> Save _neomake_info.loclist on the buffer also

autoload/neomake/utils.vim, tests/utils.vader
This handles fugitive buffers then properly, e.g. for the mypy maker.
=> Use fnamemodify wrapper in ExpandArgs

autoload/neomake/makers/ft/ansible.vim
Closes https://github.com/neomake/neomake/issues/2488.
=> maker: ansible: support new errorformat

autoload/neomake/makers/ft/python.vim, tests/ft_python.vader
Ref: https://github.com/python/mypy/issues/4746
=> fix(python): skip using --shadow-file with non-readable file
