- README.md
- autoload/neomake/makers/cpp.vim
I added a maker for c++ files. It uses the clang compiler.
> Add clang++ maker for cpp files

- README.md
- autoload/neomake/makers/c.vim
- autoload/neomake/makers/cpp.vim
Not everybody has clang. Since clang is a bit faster (I think) clang is the prefered maker, but I added gcc as a fallback maker.
> add gcc/g++ makers for c/c++ files

- autoload/neomake/makers/python.vim
Mostly taken from Syntactic, but prepended an extra row to `errorformat` to try and correctly identify warnings vs. errors and tag accordingly.
However I'm not sure where to place it in the list of checkers.
>Frosted is a fork of pyflakes (originally created by Phil Frost) that aims at more open contribution from the outside public, a smaller more maintainable code base, and a better Python checker for all.
https://github.com/timothycrosley/frosted
> Add Frosted maker for python.

- README.md
- autoload/neomake/makers/c.vim
- autoload/neomake/makers/rust.vim
The `gcc` maker had its exe field set to `clang`. This PR fixes that.
I also added a basic maker for the Rust programming language.
> add maker for rust and fix gcc maker exe

- autoload/neomake/makers/ft/ruby.vim
This add the ruby checker the way syntastic checks, so if you do not have rubocop you can at least have basic checks from the ruby interpreter.
The syntax was not build by me, I borrowed from syntastic.
> Add ruby checker to neomake

- autoload/neomake/utils.vim
Just stumbled upon the TODO while reading the code, so here is a solution.
Disclaimer: I have not actually tested the code on other platforms, but it did not break anything on my Linux and according to https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx all the format characters used here are supported on Windows.
Edit: just realized the call to `cat` below is not cross-platform, but I am not aware of an easy way in Vimscript to append a string to a file (without reading the entire file first).
> Use Vim builtin 'strftime' to create timestamps in logs.

- autoload/neomake.vim
Referring to temporary files by their full, expanded path allows neomake to still find the temporary file if the working directory changes between the moment where the temp file is created and the moment it should be deleted.
This is a corner case, but as I am testing #59 I am forcing neomake to write a temporary file each time it performs a check, and in combination with the plugin [vimfiler](https://github.com/Shougo/vimfiler.vim) which temporarily changes the working directory when performing a rename, I have temp files laying around after a rename.
> Delete the temporary file even if the working directory has changed.

- autoload/neomake.vim
Just found another "TODO Make this cross platform". 
I am a Vimscript newbie, so I am not sure why this trick with `cat` was used in the first place. My tests did not reveal a difference between the two versions.
> Do not use 'cat' to create a temp file.

- autoload/neomake.vim
Some makers (e.g. rubocop running on JRuby) may take a few seconds to return the first error (in this case, because of the JVM startup time). Neomake currently removes all signs and errors as soon as `:Neomake` is called, but this is a problem with makers that take a while to start.
For instance, I have bound `:Neomake` to `Bufwrite`. Let's assume that a maker gave two errors, one on line 1 and one on line 2. If I fix the first error, then (out of habit) type `:w`, I have to wait a few seconds before the error on line 2 appears again.
With this PR, signs and errors are not cleared when `:Neomake` is called, but when the first maker starts returning an error or is finished. This helped my workflow with JRuby, and may be useful when #46 is implemented, as building/checking large projects …
> Wait for the next maker first error (or end) to remove signs.

- autoload/neomake.vim
`b:neomake_signs_cleared` is set in the buffer where `:Neomake` is called, but if a maker returns
errors in another buffer, then this variable won't be defined.
Should fix #64.
> Check that b:neomake_signs_cleared exists before reading it.

- autoload/neomake/makers/ft/python.vim
This line broke "jump-to-error-line" from the location window. This is something I added in https://github.com/benekastah/neomake/pull/45 which wasn't included by Syntastic, I thought it would produce a bit more exhaustive match with error type (`%t`) and error number (`%n`), but it seems like it broke more than it added.
> Remove flaky error format from Frosted (Py) checker.

- autoload/airline/extensions/neomake.vim
- doc/neomake.txt
Add statusline extension for vim-airline. The lines got a bit long, do you want me to wrap them?
It's that `E:4` to the right:
> Add vim-airline extension.

- autoload/neomake.vim
- plugin/neomake.vim
Closes #72 #74.
This is a direct adaptation of the existing code to make it work, but the new API should allow further improvements: cleaner code thanks to the `opts` parameter of `jobstart`, proper handling of exit code...
> Adapt job spawning and handlers for Neovim new job control API.

- README.md
Related to #75, to help users who update neomake without having updated neovim.
> Add a note in the README about the minimum Neovim version required by Neomake.

- autoload/neomake/makers/ft/scss.vim
[Sass](http://sass-lang.com/) is a langage that extends and compiles into [CSS](http://en.wikipedia.org/wiki/Cascading_Style_Sheets); [`scss-lint`](https://github.com/brigade/scss-lint) is a linter for Sass.
> checker for Sass

- autoload/neomake/makers/ft/elixir.vim
...using the system's `elixir` executable. This will catch more basic syntax errors.
> basic elixir checker

- autoload/neomake/signs.vim
#97 uses `:language` to change locale to `en_US.utf8`, which is not available on Windows. In this case we only need to set language for messages, so `:language messages` should work fine (and it works on Windows).
> Use :language messages instead of :language

- autoload/neomake.vim
- autoload/neomake/makers/ft/ruby.vim
- doc/neomake.txt
This is a possible solution to #94: allow makers to change entries in the quickfix or location list before they are further processed by neomake (in the rubocop case, normalize the error type to 'W' or 'E').
`mapexpr` is not really adapted for this case, since to accurately find out what to change in rubocop output we would need to parse its output like `errorformat` does. I find it more robust to work on the entry objects.
The post processing function for rubocop comes from Syntastic.
> Add a way to alter quickfix or location list entries.

- autoload/neomake/utils.vim
The neomake#GetMaker interface changed (in f29e7e1de76ca7c9e3f3ae2e6a2e384c400a8436) and therefore only default makers
were returned. This broke the check for makers that changed the exe name
(ie. ruby#mri).
> Fix availability check

- autoload/neomake/signs.vim
Does that variable have a purpose, or is it just a leftover?
This commit removes all occurrences of this variable, since it can only have the value `{}`, but maybe there is a detail I am not aware of.
Edit: same remark for s:modified_signs.
> Remove s:last_modified_signs.

- autoload/neomake/makers/ft/php.vim
This adds maker recipes for PHP lint (php -l) and PHP_Codesniffer.
phpcs is configurable with a standard, which can change depending on each projects conventions. I have added the posibility to set `g:neomake_php_phpcs_args_standard` depending on the needs. This seems to be the standards used in the D recipe.
> Added maker for php and phpcs

- autoload/neomake.vim
There are 3 changes:
* Change `GetMaker` parameter to `maker_id` so it's clear that it's not always a name
* Set default `errorformat` to something that is usable
* use `maker.name` for the config vars instead of `a:name` since it could be a dictionary
Fixes #109
> Fix NeomakeSh maker generation

- autoload/neomake.vim
The issue is explained in the commit message but the long and short of it is that when `copy()` was used instead of `deepcopy()` the filename would be appended to the args list again each time `MakeJob()` was called.
This becomes an issue if the executable takes a set number of arguments or if passing the filename more than once has undesirable consequences.
> Deepcopy returned maker in GetMaker.

- autoload/neomake/makers/ft/haskell.vim
This is almost a copy of ghc-mod's maker, but without the null byte check. ghc-mod doesn't quite build with the new version of GHC (7.10.1), at least on my machine, but hdevtools does almost the same thing in a daemonised form and builds nicely.
> Add maker for Haskell's hdevtools.

- README.md
- autoload/neomake/makers/ft/erlang.vim
Use erlc as a syntax checker for erlang code.
> Add maker for erlang

- autoload/neomake/makers/ft/haskell.vim
This simply requests hdevtools to pass the -Wall parameter to GHC when it is running.
> Make hdevtools emit warnings as well as errors.

- autoload/neomake.vim
- doc/neomake.txt
> Add an option to remove invalid entries from the location/quickfix list.

- autoload/neomake.vim
I'm a vimscript novice, so apologies in advance if this isn't the ideal solution, but this seems to fix #135. Looks like it was checking the existence of `neomake_foo_enabled_makers` instead of `g:neomake_foo_enabled_makers`.
> Fix enabled makers setting

- autoload/neomake/makers/ft/rust.vim
rustc has a '-Z no-trans' flag that, when on, skips the costly LLVM code
generation phase, while still reporting all errors and warnings.
Enabling this flag makes linting much faster. It also renders "-o /dev/null"
unnecessary.
> Rust: faster checks by skipping codegen

- autoload/neomake.vim
Filetypes are treated as parts of variable names (using eval()). However, some
characters are legal in a filetype but not in an identifier. This caused the
Neomake command to completely fail when the current filename contained such
characters.
This commit fixes that by replacing all such characters with underscores ('_').
fixes #140
> Escape special characters in filetypes

- README.md
- autoload/neomake/makers/ft/python.vim
This adds a maker definition for pylama, which is a meta-checker that covers pep8, pep257, pyflakes, mccabe, pylint, and gjslint.
> Add support for pylama

- plugin/neomake.vim
Without this change, :NeomakeSh does not give any visible output unless the user manually set its errorformat before running the command.
> Show command output in quickfix list with :NeomakeSh.

- README.md
- autoload/neomake/makers/ft/typescript.vim
TypeScript Checker for TS 1.5.
There is no simple way to skip code generation for TS1.4-. But at least I hope this can make the best of evergreen TS compilers. Please refer to https://github.com/scrooloose/syntastic/pull/1382 for more info
> Add TypeScript Checker

- README.md
- autoload/neomake/makers/ft/javascript.vim
This is a style checker for JavaScript.
I'm wondering if there are rules for ordering multiple checkers for the same type.  In this PR, I went with "reverse alphabetical order" since it matched what was already here, but it would be good to know if there was something else.
> Add JavaScript maker jscs

- README.md
- autoload/neomake/makers/ft/vim.vim
This adds a Vimscript maker file using Python-based linter, [vint](https://github.com/Kuniwak/vint).
> Add vimscript maker.

- autoload/neomake/utils.vim
looks like this code was copied from syntastic and missed the `s:_width` definition: https://github.com/scrooloose/syntastic/blob/31cba018b381feb99c75a67abde7acc69daf2c50/autoload/syntastic/util.vim#L173
> fix long messages

- autoload/neomake/makers/ft/typescript.vim
Fixes this issue:
```
-f option is no longer available. Supply files directly to the tslint command instead.
```
> Fixed tslint maker args

- autoload/neomake/makers/ft/ruby.vim
While I had trouble reproducing it, sourcing my .nvimrc would
occasionally cause the following error:
```
Error detected while processing /Users/patrick.regan/.vim/bundle/neomake/autoload/neomake/makers/ft/ruby.vim:
line   40:
E122: Function neomake#makers#ft#ruby#mri already exists, add ! to replace it
Error detected while processing function <SNR>136_NeomakeCommand..neomake#GetEnabledMakers..neomake#utils#GetSortedFiletypes..CompareFiletypes:
line    1:
E171: Missing :endif
Error detected while processing function <SNR>136_NeomakeCommand:
line    2:
E171: Missing :endif
```
Adding the `!` character forces the function to be overwritten.
> Add ! To MRI Function To Fix 'Exists' Error

- README.md
- autoload/neomake/makers/ft/javascript.vim
Enables "standard" as a built-in maker for javascript. See
https://github.com/feross/standard
> Adds standard javascript maker

- README.md
- autoload/neomake.vim
- autoload/neomake/makers/ft/go.vim
- doc/neomake.txt
This PR adds an `append_file` option to the filetype maker specification. If `append_file` is 0, the file path will not be implicitly added to the arguments list. This option is useful for makers such as `go build` and `tsc` that should be run for certain filetypes but are typically run without a file argument. `append_file` is 1 by default to preserve backward compatibility.
The `go` filetype builder has been modified to set `append_file` to 0.
References #196
> Allow file to be excluded in filetype makers

- autoload/neomake/makers/ft/javascript.vim
This PR adds the `eslint_d` JavaScript maker. It wraps `eslint` and avoids delays by preloading the required modules (see [here](https://github.com/mantoni/eslint_d.js)). Its usage is identical to `eslint`.
> Add eslint_d maker

- autoload/neomake/makers/ft/haskell.vim
When ghc-mod doesn't include `Warning` in the error message it's an error
> Make ghc-mod's messages errors by default

- autoload/neomake.vim
- doc/neomake.txt
Closes #217 
Previously setting overrides for just the current buffer wasn't possible:
`let b:neomake_javascript_eslint_args = ['-c', '.eslintes6rc', '-f', 'compact']`
This now allows us to set different rules easily for a certain buffer
type.
```vim
autocmd BufRead,BufNewFile *.es6 call s:setupES6File()
let g:neomake_javascript_enabled_makers = ['eslint']
let g:neomake_javascript_eslint_args = ['-c', '.eslintrc']
function! s:setupES6File()
setfiletype javascript " Set filetype
" For the current buffer, use the special es6 eslint ruleset
let b:neomake_javascript_eslint_args = ['-c', '.eslintes6rc']
endfunction
```
> Allow b: variables for overriding maker settings

- README.md
- autoload/neomake/makers/ft/c.vim
- autoload/neomake/makers/ft/cpp.vim
`g:neomake_c_clangtidy_args_conf` needs to be properly set, especially with the `-p` option indicating the build directory containing the compile command database.
> Add clang-tidy support

- autoload/neomake/makers/ft/tsx.vim
This PR adds typescript support for TSX. It mostly just leverages the typescript libray for this, but ensures the compile gets the `--jsx preserve` args for tsx files.
> Add tsx support

- autoload/neomake/makers/ft/python.vim
Flake8 uses the prefix "F" for PyFlakes codes.  These are a mix of
warnings and errors, so we'll just treat them all as errors.
> Added postprocessing hook for flake8.

- autoload/neomake/makers/cargo.vim
The current cargo `errorformat` does not display what actually triggered the error. This PR adds the reason message, as well as some additional text from the message.
Parts of the message that are not indented are not displayed because
1. It is difficult to distinguish message text from other text (like help messages).
2. It greatly increases the size of the message with likely unnecessary information.
I am also going to attempt to get this `errorformat` merged into `rust.vim` upstream. That `errorformat` at least handles *what* triggered the error (e.g., "mismatched types"), but it does not display the additional text ("expected `collections::vec::Vec<u8>`,    found `&char`").
> Improve cargo errorformat

- autoload/neomake/makers/ft/tex.vim
This parses for example the following warning from rubber-info:
```
/home/gebner/maxsatalg/maxsatalg.tex:576-587: Underfull \hbox (badness 1132) (page 7)
```
> rubberinfo: recognize multi-line errors

- autoload/neomake/makers/ft/python.vim
Fine-tune the error types of the flake8 python checker to my personal
liking.
Exclude pep257 from flake8, because pep257 already integrates with
flake8 when flake8-docstrings is installed.
> Finetune error types of flake8

- autoload/neomake.vim
- autoload/neomake/makers/mvn.vim
- autoload/neomake/utils.vim
This PR adds Windows support to Neomake and adds a maker for Apache Maven (https://maven.apache.org/). Thanks to @equalsraf, this actually appears to be working. Because Maven is a project based builder, it was necessary to introduce the mvn maker outside of the `ft` directory. It can be invoked thusly: `Neomake! mvn`. Because the exact arguments that one uses to invoke Maven vary so widely between projects, it is recommended to override the default `install` argument by specifying:
````
let g:neomake_mvn_args=['package', '-P', 'unitTests', '-T', '2']
````
> [RDY] Add Windows support and Apache Maven builder

- autoload/neomake/makers/ft/python.vim
Add postprocess function for pylint and pep8 makers to correctly set
entry types.
> Fix entry types for pylint and pep8 checkers

- README.md
- autoload/neomake/makers/ft/pug.vim
Since [Jade has been renamed to Pug](https://github.com/pugjs/jade/issues/2184), so too has the [linter](https://github.com/pugjs/pug-lint).
This is essentially a copy of the previous [maker for Jade](https://github.com/benekastah/neomake/blob/82fb2d2183cf9143cf17b0641b84921f0495c81d/autoload/neomake/makers/ft/jade.vim).
> added pug-lint for pug filetype

- autoload/neomake/makers/ft/javascript.vim
The latest JSCS uses `--no-colors` and not `--no-color`
> Fix typo in color CLI option for JSCS maker

- README.md
- autoload/neomake/makers/ft/yaml.vim
yamllint [1] is a linter for YAML files. It does not only check for
syntax validity, but for common cosmetic conventions such as lines
length, trailing spaces, indentation, etc.
[1: http://yamllint.readthedocs.org/](http://yamllint.readthedocs.org/)
> Add YAML maker: yamllint

- autoload/neomake.vim
Using `keys()` on the `union` dict does not retain the order, which is
important for the python makers, where `python` should be run first, and
`pylint` last (in serialized mode).
> Keep order of enabled makers

- autoload/neomake/makers/ft/python.vim
This makes it easier to see what gets used.
> pylint: use long option names

- autoload/neomake/makers/ft/python.vim
When using Vim instead of Neovim, the python maker failed like this:
> Neomake: python stdout:   File "<string>", line 2
> Neomake: python stdout:     from sys import argv, exit\
> Neomake: python stdout:        ^
> Neomake: python stdout: SyntaxError: invalid syntax
> Neomake: python stdout:
> Neomake: python stdout done.
> Neomake: python processing 5 lines of output
> Neomake: File-level errors cleaned in buffer 1
It seems like we have to use "\r" for newlines, instead of "\n".
> Fix python maker for Vim: use \r instead of \n

- autoload/neomake.vim
- doc/neomake.txt
- plugin/neomake.vim
This is a rather huge refactor.
Fixes https://github.com/benekastah/neomake/issues/350 and
https://github.com/benekastah/neomake/issues/348.
It removes 'winnr' from 'maker'.
The behaviour changes so that the output is only processed by windows,
but not buffers.  This means that `Neomake | sp` will not open the
location list, until you go to the previous window.
> Process job output by window instead of buffer

- autoload/neomake/makers/ft/python.vim
Without this, flake8 may read local configuration and pickup an output format which is incompatible with the errorformat defined in neomake.
> Specify format for flake8 that errorformat actually parses.

- autoload/neomake/makers/ft/rst.vim
The maker for reStructuredText does not match warnings, only errors and infos. Fixed it. You can test it with this snippet of reStructuredText:
```
Some content.
Hello World
=======
Some more content!
```
The underline is too short, so a warning will be emitted.
> Match warnings in 'rst-lint'.

- autoload/neomake/makers/ft/angular.vim
- autoload/neomake/makers/ft/jasmine.vim
- autoload/neomake/makers/ft/jsx.vim
- autoload/neomake/makers/ft/node.vim
Given that `eslint_d` is essentially a drop in replacement for `eslint`, I thought it would be a reasonable addition to add `eslint_d` maker support wherever `eslint` is supported in javascript's supersets.
> Enable eslint_d maker for javascript supersets

- autoload/neomake/makers/ft/sh.vim
I did the following improvements to the shell makers:
- fix error type returned by shellcheck
- add optional `checkbashism` maker
- add maker using shell
For the last one, I try to detect the correct shell from the first line of the script, otherwise use `/usr/bin/sh`.
> Improve shell makers

- autoload/neomake/makers/ft/javascript.vim
Removing the (full) check argument for flowtype. It makes the maker very slow and works fine without. I think full checks on project code should be part of build/deploy scripts.
> Don't do full flowtype check

- autoload/neomake/makers/ft/haskell.vim
`hlint` has three message types: [Errors, Warnings, and Suggestions](https://github.com/ndmitchell/hlint#what-is-the-difference-between-errorwarningsuggestion). Currently, neomake's default hlint format only parses Errors and Warnings. This PR adds Suggestions to the error format as informational messages.
This should address issues like #339 where users mentioned the quickfix window not showing on all occasions (most likely due to missing Suggestions).
> Include hlint suggestions in error format

- autoload/neomake.vim
I have seen some error, where s:loclist_nr[winnr()] was not set, which
was probably caused by the window having changed after `laddexpr` was
called.  This reverts a part of 9d7d3f8.
> Get winnr once before calling AddExprCallback

- autoload/neomake/makers/ft/sh.vim
`#! /usr/bin/env bash` is apparently a valid/used shebang (yes, with a
space even).
Followup to #362.
> Fix shebang parsing in neomake#makers#ft#sh#sh

- .vintrc.yaml
E.g.
> Make the scope explicit like `l:jobinfo`
Ref: https://github.com/neomake/neomake/pull/425#issuecomment-219907955.
/cc @sbdchd
> Add .vintrc.yaml to disable style warnings about local scope

- autoload/neomake/makers/ft/java.vim
This also prefers Python 3 instead of 2.
> Fix Vint error in java maker's s:ReadClassPathFile

- autoload/neomake/makers/ft/java.vim
Found by vimlint.
There are still some more though:
```
autoload/neomake/makers/ft/java.vim:137:31:Error: EVL103: unused argument `a:classpathFile`
autoload/neomake/makers/ft/java.vim:369:65:Error: EVL104: variable may not be initialized on some execution path: `l:cp`
autoload/neomake/makers/ft/java.vim:359:29:Error: EVL102: unused variable2 `l:classes`
```
/cc @wsdjeg
> java: fix some (linting) errors

- autoload/neomake/makers/ft/go.vim
Wrongfully broken in 5ac6c80, golint behaves differently in contrast to the core go toolchain
> go: Fix golint maker

- autoload/neomake/makers/ft/perl.vim
The original perlcritic was not working because it had neomake#makers#ft#**vim**#EnabledMakers instead of neomake#makers#ft#**perl**#EnabledMakers.
Added **perl** maker for syntax checking.
> Working Perl maker with perl & perlcritic

- autoload/neomake.vim
This allows getting the list of jobs, without printing them.
> Add neomake#GetJobs

- autoload/neomake.vim
- doc/neomake.txt
This makes shellcheck pass &ft in case there is no shebang.
Fixes https://github.com/neomake/neomake/issues/373.
> Allow for maker.args to be a callback and use it for shellcheck

- autoload/neomake/makers/ft/sh.vim
This is apparently used on Travis, but makes sense in general - e.g.
probably still for Ubuntu systems?!
> Fix sh maker: recognize output format without 'line' from dash

- autoload/neomake.vim
Don't append the filename to the makeprg when it exists in the maker's args in ANY position
This is for cases like `phpmd` where the args are specifically `phpmd [filename|directory] [report format] [ruleset file]`
Currently since `%:p` is the first argument in `args`, neomake will append the filename, causing an extra argument, e.g. makeprg will be:
`phpmd ~/mu-plugins/nda-fbia/facebook.php text ruleset.xml ~/mu-plugins/nda-fbia/facebook.php`
(note facebook.php file is added twice)
While phpmd will still run like this, it is better to adhere to the exact syntax a maker expects and there is no other way to specify this (e.g. implementation of a boolean `b:neomake_ft_maker_append_file` would suffice as well)
I don't believe this will break any makers
> Don't append_file to makeprg if in args

- tests/_setup.vader
This is needed when running Vader from inside of Vim itself, to not mess
with the user's setting.
> tests/_setup.vader: restore g:neomake_verbose

- autoload/neomake.vim
- doc/neomake.txt
This allows to invalidate caches, e.g. for the statusline etc.
> Trigger NeomakeMakerFinished User autocmd on maker exit

- README.md
- autoload/neomake/makers/ft/vim.vim
This assumes that you have some wrapper script like this:
```
% cat ~/bin/vimlint
#!/bin/sh
~/Vcs/vim-vimlint/bin/vimlint.sh -l ~/Vcs/vim-vimlint -p ~/Vcs/vim-vimlparser "$@"
```
> vim: add vimlint maker

- autoload/neomake.vim
- tests/lists.vader
An alternate approach would be to look at the `postprocess` return status, but that is not backward compatible.
TODO:
> postprocess: if entry was changed, update the list

- autoload/neomake/makers/ft/vim.vim
Broken in https://github.com/neomake/neomake/pull/491.
/cc @wsdjeg
> vim: fix vint maker: "-f" specifies the format

- autoload/neomake/signs.vim
just added guards wherever `sign ` is called in case someone is running (n)vim without `+signs`
I sometimes use neomake on regular vim (which is supported by this plugin according to its docs) on older systems that are distributed with vim 7.4 compiled `-signs`
> check for +signs

- autoload/neomake/statusline.vim
- tests/statusline.vader
It would return the same as 'all', since `0 ==# 'all'`!
> Fix neomake#statusline#LoclistCounts(0)

- autoload/neomake/makers/ft/scss.vim
Seems like the scss-lint format has changed, this updated rule should
cope with the new schema.
> Update the SCSS linter errorformat

- autoload/neomake/makers/ft/python.vim
Fixes #336 for the mypy maker for python.
> python mypy maker: add type to errorformat

- autoload/neomake/makers/ft/javascript.vim
Fixes https://github.com/neomake/neomake/issues/336#issuecomment-217201458.
> javascript makers: use %E in errorformat

- autoload/neomake.vim
- tests/neomake.vader
This was broken in https://github.com/neomake/neomake/pull/352.
Fixes https://github.com/neomake/neomake/pull/352#issuecomment-238693727.
> Fix neomake#CancelJob: pass correct arg to jobstop()

- autoload/neomake/makers/ft/java.vim
Right now setting `g:neomake_java_checkstyle_xml` to use a custom checkstyle configuration xml does not work. It is because someone added _g:_ also to the string that is searched for in the defined global variables by mistake.
I noticed that when I was trying to use neomake with checkstyle so I propose this simple fix.
> Fix checking if checkstyle xml has already been set

- autoload/neomake/makers/ft/elixir.vim
This pull request fixes the following error : 
```
Error detected while processing [...]/neomake/autoload/neomake/makers/ft/elixir.vim:
line   29:
E746: Function name does not match script file name: neomake#markers#ft#elixir#dogma
Error detected while processing function neomake#Make:
line    3:
E171: Missing :endif
```
> [elixir] Fix typo in function namespace

- tests/_setup.vader
- tests/integration.vader
- tests/utils.vader
This is meant for `executable` to pick them up.
> tests: add NeomakeTestsEnsureExe to add names to $PATH

- autoload/neomake/makers/ft/sh.vim
- tests/sh.vader
This avoids the warning from shellcheck in case if there is no shebang.
This does not parse / look closely on any existing shebang line on purpose.
Ref: https://github.com/neomake/neomake/pull/409#issuecomment-219785830
/cc @lverweijen
> sh: pass in filetype to shellcheck

- autoload/neomake/utils.vim
Without this, you would see a hit-ENTER prompt in the default setup,
with `autocmd BufWritePost * Neomake` and `let neomake_verbose = 3`:
"test.js" 1L, 8C written
Neomake: Starting: eslint -f compact …
Press ENTER or type command to continue
> neomake#utils#LogMessage: call redraw before echo

- .travis.yml
- Makefile
Currently it does not work with Travis' Vim though: https://github.com/machakann/vim-vimhelplint/issues/5.
Let's wait on that issue.
Alternatively we should/could use a Docker based approach for the tests anyway.
> Travis: add vimhelplint

- README.md
- autoload/neomake/makers/ft/python.vim
[py3kwarn](https://github.com/liamcurry/py3kwarn) detects code that is not Python 3 compatible.
> python: Add py3kwarn maker

- autoload/neomake/makers/ft/puppet.vim
As you can see in [the syntastic implementation for `puppet parser validate`](https://github.com/scrooloose/syntastic/blob/59cc80a8f7f7544a364814622dc62efd00d17ca4/syntax_checkers/puppet/puppet.vim#L27), later versions of puppet need to be told to avoid colorized output to parse correctly.
I looked through the existing makers to find if there was prior work regarding logic to set checker flags based on executable version but couldn't find anything; but based upon syntastic's logic it looks like only _pretty_ old versions of puppet won't recognize the flag (< 2.7.0, released in 2011) so this feels relatively safe to me.
> Specify --color=false in puppet parser validate output

- autoload/neomake/makers/ft/python.vim
It is useful to know the flake8 error code when you need to: (a) look it up in documentation, or (b) suppress it by updating the flake8 config or directive in the code comments (e.g. `# flake8: disable=F401`).
Currently, the status line message does not show the error code, just the message:
```
flake8: 'foo' imported but unused
```
This PR adds the error code to the message, as follows:
```
flake8: F401 'foo' imported but unused
```
> Add flake8 error code to displayed error message

- README.md
- autoload/neomake/makers/clippy.vim
Clippy is a rust linter that has more lints than standard rustc (`Neomake! clippy` will show the rustc/cargo lints as well as the clippy ones).
Since clippy integrates with the rust compiler, it has the same errorformat (I copied the error format from #613). Clippy needs a nightly compiler to work. Since it is the most convenient way, `rustup` (manages multiple rust installations) is used if available to run clippy with nightly rust, while other compilations can use stable rust.
I also added cargo and clippy to the Readme, with the annotation that `Neomake!` needs to be used (wasn't obvious for me).
> Rust clippy maker

- autoload/neomake/makers/ft/go.vim
According to golint the linter is giving style errors which imho should be considered as warnings instead of errors.
```
Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes.
Golint differs from govet. Govet is concerned with correctness, whereas golint is concerned with coding style. Golint is in use at Google, and it seeks to match the accepted style of the open source Go project.
The suggestions made by golint are exactly that: suggestions.```
> Add golint as Warning instead of Error

- autoload/neomake/utils.vim
Fixes https://github.com/neomake/neomake/issues/650.
> neomake#utils#redir: do not use execute with Vim for now

- plugin/neomake.vim
Doing in the plugin file directly seems unclean, but only doing it for
ColorScheme will not be triggered for the `:colorscheme` in a vimrc.
> Call neomake#signs#DefineHighlights on VimEnter

- autoload/neomake/makers/ft/cpp.vim
These checkers should be enabled by default for C++ files as well as C files
> Adds c clang-tools to cpp makers

- autoload/neomake/signs.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
If e.g. "Error" is defined to have red for the fg (as with the gotham
theme (https://github.com/whatyouhide/vim-gotham/issues/27)), then
switch the "fg"/"bg" attributes.
Fixes https://github.com/neomake/neomake/pull/659.
> Improve neomake#signs#DefineHighlights to switch bg/fg

- Makefile
This gets not removed after the tests for now (but could).  Should be
isolated enough this way.
> testnvim: use HOME=build/neovim-test-home

- Makefile
- tests/vim/vimrc
I've used a symlink before, but that conflicted with adding Docker
support, which did not resolve the symlink but added it as-is.
This makes it easier to hack on Vader from a local checkout.
> tests: allow for tests/vim/plugins/vader.override

- autoload/neomake/makers/cargo.vim
- autoload/neomake/makers/clippy.vim
- autoload/neomake/makers/ft/rust.vim
This PR closes #592. Stable 1.12 version of Rust, which introduces new errorfmt as default, will land in a few days and i think that it's reasonable to switch to the new errorfmt.
Introduced makers try to remove unnecessary informations, while maintaining error/warning messages, error description taken from the pointer line and note/help lines. The only thing that is missing is proper parsing of error/warning width, as pointer line contains both markers (^^^^) and error description.
More information about new format can be found [here](https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html). I decided against parsing lifetime messages, because in my opinion they can't be shown in a sane way.
> New errorfmt for Rust

- autoload/neomake.vim
- tests/neomake.vader
This gets displayed by default and the job id is not relevant and rather
confusing there.
> Do not add jobid to QuietMessage for "completed with"

- .travis.yml
- Dockerfile.tests
- Makefile
- README.md
- autoload/neomake.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
- tests/utils.vader
Followup of https://github.com/neomake/neomake/pull/575.
The main hack being https://github.com/neomake/neomake/pull/636/commits/650d4562aac94e4198e3f3b397fa786b582cf7e4 probably, but other crucial things were changed, e.g. using "raw" mode to behave the same as Neovim does - for non-buffered output.
TODO
> Vim async, take 2

- autoload/neomake.vim
The "sh -c" wrapper does not work there like it is, and might not be an
issue in normal (non-test) use cases.  Should be fixed by some Vim patch
anyway soon.
Ref: https://www.reddit.com/r/vim/comments/56jall/neomake_async_make_linting_framework_supports_vim/d8knvud.
> Disable vim8 sleep-hack for Windows

- doc/neomake.txt
The example code in the documentation for `neomake#signs#RedefineErrorSign` calls said function as `neomake#utils#RedefineErrorSign` which is not defined (probably it was moved/renamed?). This commit fixes this discrepancy.
> Typo in examplecode for RedefineErrorSign

- autoload/neomake.vim
This causes spurious build failures.
> HACK: Vim might fail to stop a job right away.
> So let's just wait a bit, which is OK since this is not really
> a user facing function anyway.
> https://github.com/vim/vim/issues/1155
From: https://github.com/neomake/neomake/pull/697.
> Vim-async: cherry-pick sleep hack for neomake#CancelJob

- autoload/neomake/utils.vim
This relies on Vim/Neovim to handle the escaping and detection of
"cmd.exe" itself.
> Simplify/fix neomake#utils#MakerFromCommand

- autoload/neomake.vim
- autoload/neomake/utils.vim
- tests/integration.vader
- tests/neomake.vader
Use "%m" instead with neomake#ShCommand, which makes all entries valid
there additionally.
Fixes https://github.com/neomake/neomake/issues/715
> Fix overwriting errorformat in MakerFromCommand

- Dockerfile.tests
While this removes and installs build deps twice on a clean run, it
helps when only updating master.
In the long run there should be a separate Dockerfile for vim-master
probably, and this should be moved to the vim-testbed repo probably.
> Dockerfile.tests: build vim-master separately

- Makefile
- autoload/neomake.vim
- autoload/neomake/makers/ft/go.vim
- doc/neomake.txt
- tests/_setup.vader
- tests/integration.vader
- tests/mapexpr.vader
This sets neomake_bufname, neomake_bufdir and neomake_output_source
('stdout'/'stderr') during the execution of `mapexpr`.
This combines #630 and #734.
> Execute mapexpr in ProcessJobOutput for the buffer context

- autoload/neomake/makers/ft/apiblueprint.vim
Uses drafter if it's available on the system. Recommended to use with [apiblueprint.vim](https://github.com/kylef/apiblueprint.vim) which sets the filetype.
> Add apiblueprint maker

- autoload/neomake.vim
This is still not optimal, but at least a bit better.
> s:AddExprCallback: call signs only once per run

- autoload/neomake.vim
- tests/_setup.vader
- tests/integration.vader
- tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/238.
> Use debug level for '%s: completed with exit code %d.' messages

- autoload/neomake.vim
Without this, `:Neomake! <tab>` would correctly list potential makers, but using
any of them would result in: "Maker not found".
> [RFC] Make `:Neomake! <maker>` great again

- autoload/neomake/makers/ft/scss.vim
Stylelint (http://stylelint.io/) supports CSS, SCSS, and Less. In fact, it has more [rules](http://stylelint.io/user-guide/rules/), more [published configs](https://www.npmjs.com/search?q=stylelint-config), and even more GitHub stars compared to sass-lint—I would consider it a better-supported project than the alternatives.
This adds support for Stylelint in SCSS.
> Allow stylelint in .scss

- autoload/neomake/makers/ft/less.vim
As stated in the other PR, there must be a better way rather than checking if stylelint is executable. This was modeled to be as similar as possible to the PR #665 . Also, thank you to @rstacruz for mentioning stylelint.
> Allow stylelint for .less

- autoload/neomake.vim
- tests/lists.vader
This removes s:{loc,qf}list_nr, where s:loclist_nr was using the
(unstable) winnr of the maker.
> Fix post processing of jobs when changing windows

- autoload/neomake.vim
- doc/neomake.txt
- tests/lists.vader
- tests/neomake.vader
It looks like the exit callback is not being called, like with Neovim's
`jobstop()`.
> Unlet Vim job in neomake#CancelJob

- autoload/neomake/makers/ft/sh.vim
- tests/ft_sh.vader
Simplify the function and also consider filename extensions and global variabes
from `:h ft-sh-syntax`.
Closes #776.
> Refactor neomake#makers#ft#sh#shellcheck()

- autoload/neomake.vim
This partly reverts 02e9912a (https://github.com/neomake/neomake/pull/762).
Fixes https://github.com/neomake/neomake/issues/782.
> neomake#Make: only set ft for file_mode

- autoload/neomake/makers/ft/puppet.vim
The output isn't parsed correctly, because the errorformat is missing the column. 
https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/puppet/puppet.vim
> Puppet: Add errorformat with column

- autoload/neomake/makers/ft/c.vim
The extra cmd line flags "-- -Wall -Wextra" are not accepted and
processed by clang-check, moreover they actually prevent it from working
correctly.
> clangcheck: removed flags not accepted by clang-check

- autoload/neomake/makers/ft/erlang.vim
Without this patch the erlc maker treats warning as errors.
> Make the erlc maker distinguish warnings from errors

- autoload/neomake/makers/ft/typescript.vim
Same as here: https://github.com/neomake/neomake/pull/532
I was able to get airline support only when enabled %E in error format
And it's related to https://github.com/neomake/neomake/issues/336
> tslint maker: use %E in errorformat

- autoload/neomake/makers/ft/vim.vim
Currently, neomake's `errorformat` for vint makes it  treat `style_problem` as an error. This is because the `%t%*[^:]` part of `errorformat` successfully matches `style_problem`. More acurately, `%t` matches `s` and `%*[^]` matches `tyle_problem`. Since `s` is not a valid type (ie. neither `e` for error nor `w` for warning, nor `m` for message) vim, and thus neomake, treats it as error by default. Style issues can hardly be considered errors, so this change makes vim and neomake treat `style_problem` as info.
- `%I` marks the start of a multiline info message
- `%f` matches a filename
- `%l` matches the line of `style_problem`
- `%c` matches the column of `style_problem`
- `style_problem` matches a litteral "style_problem", just like ':' matches a litteral ':'
- `%m` matches the message …
> [Vint] Treat style_problem as info message

- autoload/neomake.vim
- autoload/neomake/highlights.vim
- autoload/neomake/makers/ft/python.vim
- doc/neomake.txt
- plugin/neomake.vim
This PR implements #212. If the entry has a column assigned, it is highlighted, if no column is specified, nothing is done, as this would just duplicate information already visualized by the signs.
Writing this PR, I see however a comment in the issue to visualise lines. Maybe I should make it an option to highlight the complete line when no column is known. Then you could use this instead of the signs. It's easy to do, but I'll probably wait for a comment before I do.
> Highlighting of columns

- autoload/neomake/makers/ft/ansible.vim
Relies on [ansible-lint](https://github.com/willthames/ansible-lint) for linting and [vim-ansible-yaml](https://github.com/chase/vim-ansible-yaml) for filetype detection.
> Ansible file maker

- autoload/neomake/makers/ft/python.vim
All the F4* (apart from F407) should be warnings, and not errors.
> makers: python: improve preprocessing of flake8 entries

- autoload/neomake/makers/ft/elixir.vim
The current directory is the default, and should rather be set during
evaluation.
> maker: elixir#mix: remove getcwd()

- autoload/neomake.vim
Fixes #835 
The docs say that `g:neomake_higlight_lines` is 0 by default. It wasn't. Now it is. 
This also fixes `g:neomake_highlight_columns` not being respected.
> Fixes #835 Bad default for g:neomake_highlight_lines

- autoload/neomake/utils.vim
- tests/utils.vader
This allows for using '%s' as argument, e.g. with ['printf', '%s\n',
'1', '2'], and removes the weird rule to expand items starting with
backslash, but not with backslashes only inside.
> Fix/simplify neomake#utils#ExpandArgs

- autoload/neomake.vim
Should be done similar to `neomake#utils#getbufvar` instead anyway.
> Remove s:getwinvar: not required currently

- autoload/neomake.vim
- doc/neomake.txt
- tests/args.vader
- tests/neomake.vader
Fixes https://github.com/neomake/neomake/issues/837.
Closes https://github.com/neomake/neomake/pull/841.
TODO
> Allow for maker.args to be a string, skipping quotation/escaping

- autoload/neomake.vim
- autoload/neomake/utils.vim
- plugin/neomake.vim
- tests/include/setup.vader
- tests/integration.vader
- tests/lists.vader
- tests/neomake.vader
- tests/processing.vader
- tests/signs.vader
https://github.com/neomake/neomake/issues/805
TODO
> Refactor output processing to only be done in insert/normal mode

- autoload/neomake/makers/ft/text.vim
It is used as fallback often, and e.g. 'proselint' does not make sense
then.
> [RFC] Do not enable makers by default for ft=text

- Makefile
It does not seem to be possible to get colors through from Vim itself, so this just wraps `sed` around it to add some highlights.
/cc @junegunn
> Makefile: highlight lines containing '(X)' in red

- autoload/neomake/makers/ft/javascript.vim
Remove [deprecated](https://github.com/facebook/flow/issues/2844) `--old-output-format` in favor of `--from-vim`. Output looks alright now.
Should fix #241.
> Fix flow output

- autoload/neomake/makers/ft/javascript.vim
`--from-vim` → `--from vim`
Sorry about that.
Closes #876.
> javascript: fix typo on flow args

- autoload/neomake/makers/ft/sh.vim
- tests/ft_sh.vader
I've added support for the [shellcheck] directive [#shellcheck shell=].
See #747 and the thread beginning at [my last comment](https://github.com/neomake/neomake/pull/747#issuecomment-268690807) for more information on this request. The reason I added support for testing the version of shellcheck in #747 was that the [#shellcheck shell=] directive was only added in 0.4.4. Considering that caused so much discussion I guess we can make the assumption that if a user is editing a file with a [#shellcheck shell=] directive then they have the appropriate version of shellcheck.
[shellcheck]: https://github.com/koalaman/shellcheck
[#shellcheck shell=]: https://github.com/koalaman/shellcheck/wiki/Directive
> Add support for "#shellcheck shell=" directive

- autoload/neomake/makers/ft/javascript.vim
Flow support was totally broken `'--from vim'` did not work, it should either be `'--from', 'vim'` or like I did `'--from=vim'`. This also improves the error message in general and adds support for the length of underline.
> Javascript: Fix flow argument and add support for entry.length

- autoload/neomake.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
- tests/integration.vader
- tests/neomake.vader
It is explained in the doc:
> it was changed because it is usually better to see unhandled output in
> case something is not working as expected, e.g. when the program
> displays some error.  Makers should handle this properly through
> |errorformat|, e.g. by using '%-G' (see |efm-ignore|).  You can
> specify the default for this via |g:neomake_remove_invalid_entries|.
> Change default for remove_invalid_entries to 0

- autoload/neomake/utils.vim
- tests/utils.vader
`strpart` handles bytes, which might cut strings like the following in
the middle of multibyte characters, resulting in a longer string (and
causing a hit-ENTER prompt):
> typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
> Fix neomake#utils#WideMessage for multibyte strings

- autoload/neomake/makers/ft/python.vim
pylint uses 0-indexed columns, vim uses 1-indexed columns
This bug might exist in flake8, too, but i'm not sure (I don't use it).
> [pylint] fix column off-by-one

- autoload/neomake.vim
- autoload/neomake/utils.vim
- tests/utils.vader
This will sort the list of line entries by their distance to the current
column (preferring entries starting at or after the current position).
Previously the first entry (preferring those of type "error") was
displayed always.
Therefore the function needs to be called in neomake#CursorMoved now
always again.
> neomake#EchoCurrentError: display nearest entry (sorted by col)

- autoload/neomake/makers/ft/elixir.vim
Some of the message are line-wise and have no column.
> Support elixir credo checker messages without colum

- autoload/neomake/makers/ft/ruby.vim
I had this from somewhere in my local stash - maybe from Syntastic?!
@Neki 
Does it make sense?
> ruby: rubocop: improve errorformat

- autoload/neomake/makers/ft/racket.vim
The maker in its current form has a number of issues:
- ~The error message is prefixed with the name of the maker (`raco: bar: unbound idetifier ...`)~
- The location list seems to do some sort of pattern matching as well
- ~Pressing <CR> in the location list on the error message does not open the error, instead an error is thrown: `E924: Current window was closed`~
- If there are no errors the location list will be populated with the output of the expanded file. What I want is for the location list to either contain nothing if there is no error or contain everything if there is an error.
- ~The location list does not open automatically on error like it does for example for Python (I don't have any special settings for Python files).~
I would appreciate help in getting the details right …
> [RFC] Write first version of the Racket maker.

- autoload/neomake.vim
Otherwise the "NeomakeSh: non-existing command" test might trigger this.
Instead let it call the exit handler like expected.
This might have been necessary with older Vim versions.
> s:MakeJob: keep quickly exited Vim jobs

- tests/ft_idris.vader
- tests/processing.vader
- tests/serialize.vader
Makes tests more predictable.
Ref: https://github.com/neomake/neomake/pull/939#issuecomment-273302414.
> tests: use lgetexpr instead of laddexpr

- autoload/neomake/signs.vim
Since bufnr is used as a key to various dicts like s:sign_queue,
s:placed_signs, etc. its value is converted to string. So we have to
explicitly convert it back to number when calling bufexists() function.
It fixes an issue when calling `:Neomake! clippy` doesn't clean the old signs. Introduced by #935 PR.
> bufexists() function expects a number as a parameter.

- README.md
This obsoletes https://github.com/neomake/neomake/wiki/Running-Neomake%27s-test-suite/ then.
> doc: add a dev/hacking section to the README

- autoload/neomake/makers/ft/elixir.vim
closes #960 
Let me know if this is the way to go, or if you prefer the function inside `neomake#utils#EnforceMaxBufferLine`
> elixir mix. enforce lnum line is inside buffer length

- autoload/neomake/makers/ft/elixir.vim
They should be ignored in the .credo.exs file if the user wants to do so
> removed ignored readability checkers

- tests/integration.vader
- tests/utils.vader
Makes `vim -u tests/vim/vimrc '+Vader!' tests/integration.vader` work on
Zsh.
> tests: handle non-bash shell (set in Makefile) better

- autoload/neomake.vim
As per the title: when using `:NeomakeListJobs` to manage errant jobs, it can be hard to figure out which one was which. This proposed change simply adds the `maker.name` value on the output for each job.
> Add maker.name to neomake#ListJobs() output

- autoload/neomake.vim
- doc/neomake.txt
- tests/integration.vader
This allows entries to be explicitly removed by a `postprocess` function.
In the future, I want to add support for a user-defined `NeomakePostProcess(maker, entry)` function that's called after the maker's `postprocess` function.  This will reduce the cognitive load and the need for maintenance for an end user that just wants to alter/remove some entries without worrying about dealing with a built-in maker directly.
> [RFC] Entry removal in post-processing

- autoload/neomake/makers/ft/elixir.vim
- tests/ft_elixir.vader
- tests/neomake.vader
Adding missing mapping of entry types from elixir credo to neomake.
Full credit to @emilsoman in https://github.com/neomake/neomake/pull/300#issuecomment-244722296
> mapping credo error types to neomake

- autoload/neomake/makers/ft/python.vim
- tests/ft_python.vader
This had a similar bug, where the col (and thus also the underline) was put at
the def or import already instead of under the actual redefinition.
> Python: Use fix for flake8 column for redefinition error as well

- autoload/neomake/makers/ft/elixir.vim
Hi, semi-related to https://github.com/elixir-lang/elixir/issues/5143
`mix compile --warnings-as-errors` returns a multiline string now:
```
/tmp/foo $ mix compile --warnings-as-errors
Compiling 1 file (.ex)
warning: variable world is unused
lib/foo.ex:3
```
This PR fixes the `mix` maker, so both warnings and compilation errors are detected properly.
> Support new compilation warnings format with mix

- autoload/neomake.vim
'10' needs to be sorted after '9' for processing of job output in the
order they were started.
> Fix sorting in s:ProcessPendingOutput

- autoload/neomake.vim
- autoload/neomake/signs.vim
- tests/signs.vader
Drop signs queue: place them immediately
This removes neomake#signs#PlaceVisibleSigns and neomake#signs#RegisterSign.
Fixes: https://github.com/neomake/neomake/issues/834
Closes: https://github.com/neomake/neomake/pull/471
Ref: https://github.com/neomake/neomake/issues/240
Ref: https://github.com/neomake/neomake/pull/893
> Drop signs queue

- autoload/neomake/makers/ft/cs.vim
- autoload/neomake/utils.vim
- tests/ft_cs.vader
- tests/neomake.vader
The MSBuild uses the solution file (.sln) or the .csproj to build, so to the maker works it was needed to add a function to find the .sln file. To this maker works as well it is needed to add the MSBuild on the
environmental variable PATH.
> Added MSBuild maker

- autoload/neomake.vim
- tests/cwd-tcd.vader
- tests/neomake.vader
This way the `tcd` won't be overriden to a `cd`, messing with tab-local directory settings.
> Fix tcd changing dir

- tests/neomake.vader
This is necessary to reset After/Before after cwd-tcd.vader.
> tests: move Include in neomake.vader

- tests/include/setup.vader
- tests/utils.vader
This helps when accidentally running the utils tests twice.
> tests: improve NeomakeTestsEnsureExe

- autoload/neomake.vim
- tests/include/setup.vader
When accidentally modifying a s:jobs entry, and the key does not match
the entry's id property anymore, you should still be able to kill all
jobs.  This is mostly relevant for tests only.
> tests: call NeomakeCancelJobs! (and use keys therein)

- autoload/neomake.vim
- tests/neomake.vader
This also stores the maker from after the `maker.fn` on `jobinfo`.
Not sure about using an exception here (instead of a special return
value).
/cc @tweekmonster ^^
> Move restart check into s:MakeJob

- .travis.yml
- Makefile
- autoload/neomake/utils.vim
- contrib/highlight-log
- tests/utils.vader
It includes the relative time to the previous message now, but only if
greater than 0.01 seconds.
For `neomake_logfile`:
```
21:34:18 [V +42.9] Calling User autocmd NeomakeCountsChanged …
21:34:18 [D      ] [120] Running makers: vint
21:34:18 [V      ] [120] Starting async job: …
21:34:19 [D +1.19] [120.119] stdout: vint: …
21:34:19 [D +0.02] [120.119] exit: vint: 1
21:34:19 [D      ] [120.119] vint: processing 1 lines of output.
```
For tests:
```
(2/9) [EXECUTE] Output is only processed in normal/insert mode (qflist)
> [debug  ]: Skipping User autocmd NeomakeCountsChanged: no hooks.
> [debug  ]: [2] Running makers: sleep_efm_maker
> [verbose]: [2] Starting async job: …
> [D +0.11]: [2.2] stdout: sleep_efm_maker: …
> [debug  ]: [2.2] exit: sleep_efm_maker: 0
> [debug  ]: Not processing …
```
> Improve logging format

- autoload/neomake.vim
- tests/processing.vader
Fixes https://github.com/neomake/neomake/issues/1078.
> Vim: split output on \r\n optionally

- autoload/neomake/makers/ft/python.vim
- autoload/neomake/makers/ft/python/compile.py
- autoload/neomake/utils.vim
This makes it less verbose in the logs, and less fragile with regard to
having "newlines" in the args.
> python: python: move script into compile.py file

- autoload/neomake.vim
- autoload/neomake/utils.vim
- tests/args.vader
- tests/neomake.vader
- tests/utils.vader
- tests/verbosity.vader
This reverts db461be and fixes #959 by using `fnameescape` on each argument.
Fixes #959.
Fixes #992.
> Fix argument quoting for Vim on Windows

- autoload/neomake.vim
- tests/processing.vader
This happens at least for the vimhelplint wrapper (to come).
> Remove \r at end of lines also with Neovim

- .travis.yml
- Makefile
- autoload/neomake/makers/ft/help.vim
- contrib/vimhelplint
- tests/ft_help.vader
- tests/neomake.vader
This adds makers for Vim's help filetype, where vimhelplint is used
through a wrapper script (contrib/vimhelplint).
> Add ft makers for help files; vimhelplint wrapper

- autoload/neomake.vim
- tests/postprocess.vader
Fixes https://github.com/neomake/neomake/issues/766, but it would be
probably still better to break the API and pass it as a function/method
argument.
Still not documented, and therefore considered to be experimental.
> Improve postprocess interface

- .travis.yml
- autoload/neomake.vim
- autoload/neomake/makers/ft/neomake_tests.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
- tests/errors.vader
- tests/ft_python.vader
- tests/include/setup.vader
- tests/integration.vader
- tests/lists.vader
- tests/neomake.vader
- tests/processing.vader
- tests/serialize.vader
- tests/tempfiles.vader
- tests/utils.vader
This manages active jobs in s:make_info, and keeps track of finished
ones.
It now restarts jobs for the same maker directly, instead of waiting for
the old one to do it from the exit handler.
> Improve managing active jobs, and restart them directly

- autoload/neomake.vim
- tests/tempfiles.vader
Neomake would try to use an empty temporary file.
> Fix "E482: Can't create file <empty>"

- autoload/neomake.vim
- tests/makers.vader
In case s:MakeJob returns `{}` (e.g. because the `exe` does not exist)
we should continue with the next maker.
> s:handle_next_maker: continue with next makers

- autoload/neomake.vim
- tests/filetypes.vader
This makes it behave similar to neomake#GetEnabledMakers.
> neomake#GetMakers: return all makers with multiple filetypes

- autoload/neomake.vim
- autoload/neomake/makers/ft/angular.vim
- autoload/neomake/makers/ft/jasmine.vim
- autoload/neomake/makers/ft/jsx.vim
- autoload/neomake/makers/ft/node.vim
- autoload/neomake/makers/ft/tsx.vim
- autoload/neomake/utils.vim
- tests/filetypes.vader
- tests/integration.vader
- tests/lists.vader
- tests/makers.vader
- tests/neomake.vader
- tests/serialize.vader
- tests/utils.vader
- filetype is not split by default anymore, but a new function is added
to get a list of name for config lookups.  This will now also look at
`g:neomake_foo_bar_maker_exe` for filetype=foo.bar.
Fixes https://github.com/neomake/neomake/issues/272.
Fixes https://github.com/neomake/neomake/issues/492.
- This makes use of the optional SupersetOf callback (used by
jsx/jsx.javascript) to get makers from the parent.
Ref: https://github.com/neomake/neomake/pull/1122#issuecomment-287498327
Fixes https://github.com/neomake/neomake/issues/572.
> Fix handling of multiple fts (foo.bar)

- autoload/neomake.vim
- autoload/neomake/debug.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
- tests/include/setup.vader
- tests/integration.vader
- tests/makers.vader
- tests/serialize.vader
- tests/tempfiles.vader
- tests/utils.vader
This is meant to return quickfix/location list entries directly,
avoiding to use both `mapexpr` and `postprocess` with JSON output.
TODO:
/cc @JelteF
> Add support for maker.{process_output,get_list_entries}

- autoload/neomake/makers/ft/pandoc.vim
- autoload/neomake/utils.vim
- tests/ft_pandoc.vader
- tests/neomake.vader
SupersetOf can be chained now.
Fixes https://github.com/neomake/neomake/issues/1141.
> Fix pandoc after making markdown use SupersetOf

- autoload/neomake.vim
- tests/include/setup.vader
- tests/processing.vader
This removes jobinfo.restarting, and uses jobinfo.canceled only.
> Do not consider canceled jobs for restart handling

- autoload/neomake/makers/ft/elm.vim
- tests/ft_elm.vader
- tests/neomake.vader
This adds a maker for [Elm](http://elm-lang.org/). The compiler
errors provided by elm are quite detailed, but this only adds
handling for the base error/warning types and short messages.
This maker relies on the JSON output of elm-make and is *heavily*
based on #942 (it's basically a carbon copy).
> Add Elm maker using elm-make

- autoload/neomake/compat.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
- tests/utils.vader
It was used for neomake_logfile only, and there it does not make sense
to simulate appending to the file by writing it completely again, since
that does not work as expected with `tail -f` etc.
Without patch-7.4.503 it will now just overwrite the logfile for every
log message.
> Remove neomake#compat#writefile

- autoload/neomake.vim
- autoload/neomake/utils.vim
- tests/tempfiles.vader
Moves it to neomake#utils#write_tempfile and adds tests to ensure it
behaves like (Neo)Vims `:write` regarding the various options.
> Fix writing of temp files regarding EOL

- Makefile
- tests/vim/vimrc
This sets 'noloadplugins' to skip loading of global plugins, but only
user-defined ones (in case HOME would not be set to a temporary dir).
Vader and Neomake are then sourced manually.
> tests: cleanup/improve vimrc

- autoload/neomake/makers/ft/rust.vim
This PR introduces `cargo-check` as the default command run in the `cargo` maker. Users can set the command passed to `cargo` via specified option (`g:neomake_rust_cargo_command`). Most notably to enable test-checking support one would add this line to the .vimrc:
`let g:neomake_rust_cargo_command = ['test', '--no-run']`
This closes #843.
> Migrate to cargo-check in cargo.vim maker by default

- autoload/neomake.vim
- autoload/neomake/makers/ft/go.vim
- autoload/neomake/makers/ft/javascript.vim
- autoload/neomake/makers/ft/python.vim
- autoload/neomake/makers/ft/rust.vim
- autoload/neomake/makers/ft/sh.vim
- autoload/neomake/signs.vim
- autoload/neomake/statusline.vim
- autoload/neomake/utils.vim
VimL knows how to quickly return from empty(), so use it when
appropriate instead of unnecessarily calculating the length.
> Use empty()/!empty() in place of !len()/len()

- tests/errors.vader
- tests/ft_cs.vader
- tests/ft_css.vader
- tests/ft_vim.vader
- tests/processing.vader
- tests/signs.vader
- tests/tempfiles.vader
- tests/utils.vader
This ensures to not mess with the '[Vader-workbench]' buffer's name.
> tests: use new/bwipe with :file

- autoload/neomake/makers/clippy.vim
- autoload/neomake/makers/ft/rust.vim
- tests/ft_rust.vader
This is solves #1196. I have a several questions/ideas regarding this PR and so this is at the moment regarded work in progress.
* As `clippy` heavily uses multiple information messages in the children array I decided to leave the first message appended to the parent message, and create subsequent `I` (information) messages for each child. This way we can retain certain important information visible, without the need to open the location list (see #793 for example).
* Currently i left out the information about the spans away from the created children (code for that is commented out on purpose), granting them effectively the same span as the parent. Ideally we could use the provided span if it exists, otherwise the parent's span should be used. However I am not sure if I didn't hit a …
> Use json output in the clippy maker

- autoload/neomake.vim
- autoload/neomake/signs.vim
- tests/include/setup.vader
- tests/integration.vader
- tests/signs.vader
One of the main ideas here is to clean old signs only after new jobs have finished, where existing signs were re-used/recycled.  Only at the end old/left-over signs are removed.
This keeps existing signs for longer, which is useful while waiting for the new make run to finish, and avoids flickering in general.
> Improved sign handling

- autoload/neomake/makers/ft/javascript.vim
this makes emacs only load the required packages, rather than load everything else the user has installed by package.el, which is far slower in some cases
> speed up rjsx-mode linter

- doc/neomake.txt
Linking to `neomake.txt` does not work by default?! ('.' missing in
'iskeyword').
> doc: add Neomake help tag

- autoload/neomake/makers/ft/ruby.vim
Problem: Neomake was running rubocop on a file that had been ignored in `.rubocop.yml`
Solution: Used the recommended flag to indicate that `rubocop <file>` runs should still adhere to these exclusions. To quote a contributor [over in rubocop's github repo](https://github.com/bbatsov/rubocop/issues/2492#issuecomment-164375887):
> There's an option called --force-exclusion, which editor plugins should use. The problem is that when you give a single file name to rubocop, then Exclude parameters don't come into play. Unless you run with --force-exclusion.
> Rubocop: add --force-exclusion

- autoload/neomake/makers/ft/d.vim
The following results in '1 \2' and not '1 2':
let foo = '1 \
\2'
/cc @rsw0x (since you added it in https://github.com/neomake/neomake/pull/239)
> d: fix s:UpdateDub

- autoload/neomake/config.vim
- autoload/neomake/utils.vim
- tests/config.vader
- tests/neomake.vader
- tests/utils.vader
This will lookup config settings in b:config, g:config, and has support
for `context` (for filetype and bufnr) (where `context.maker` is also
looked at in the end).
The idea is to prefer the new format, and fallback to looking up the current scheme.
I am not sure if it should be deprecated really, since it allows for easier one-shot configs (`let g:neomake_someft_maker_args` vs `g:neomake['ft:someft']['maker']['args']`, where you have to initialize the dict(s).
`g:neomake['ft:someft']['maker']['args']` is not really supported in this PR as of now.
My main intention for this is with the automaking, where I would like to have some config namespace, i.e. `g:neomake.automake` would allow to override other settings in the `automake` context.
TODO:
> dict based config

- contrib/vim-checks
Ref: https://github.com/neomake/neomake/pull/1242#issuecomment-298015969
[ci skip]
> Add license header to contrib/vim-checks

- autoload/neomake/makers/ft/sh.vim
- tests/neomake.vader
This is useful to explicitly use `dash` as a POSIX shell, in case
`/bin/sh` links to `bash`.
> sh: add dash maker

- autoload/neomake.vim
- tests/integration.vader
- tests/neomake.vader
- tests/tempfiles.vader
- tests/verbosity.vader
This adds an extra quoting level, which makes it harder to copy'n'paste.
> Do not use string representation for non-async "Starting" message

- autoload/neomake.vim
- doc/neomake.txt
- tests/cwd.vader
- tests/makers.vader
- tests/neomake.vader
- tests/processing.vader
- tests/signs.vader
`bufnr` does not default to the job's bufnr anymore, but is expected to
be given as `bufnr` or `filename`.  The `bufnr` is then picked up from
the parsed location/quickfix list entries (where Vim will have created
an unlisted buffer for non-opened filename entries).
Ref: https://github.com/neomake/neomake/pull/1194#pullrequestreview-35487107
Ref: https://github.com/neomake/neomake/pull/1218
TODO:
> Fix bufnr handling with get_list_entries/process_output

- tests/include/init.vim
- tests/processing.vader
- tests/tempfiles.vader
This should fix flakyness of "Neomake#Make cancels previous jobs".
> tests: sleep_maker: sleep a bit more

- autoload/neomake/utils.vim
This accompanies the fix for writegood accidentally added to 90c3393.
Before this newlines would be removed altogether, but the reason for
that should be fixed somewhere else:
> This is here because it is possible for some error messages to
> begin with \n which will cause a "press enter" prompt.
> neomake#utils#WideMessage: replace newlines with spaces

- autoload/neomake.vim
- doc/neomake.txt
- plugin/neomake.vim
- tests/highlights.vader
- tests/integration.vader
- tests/processing.vader
- pending job output is not stored in the window anymore
- file mode jobs get processed in another window (for the buffer), if
the original window is gone
- autocommands are setup only when there is pending output
> Refactor pending output processing

- autoload/neomake.vim
- tests/tempfiles.vader
- do not default to `jobinfo.bufnr` anymore
TODO:
> tempfiles: fix setting bufnr of errorformat makers

- autoload/neomake.vim
This is mainly an issue during tests/development, where Vader might fail
hard without this.
> Make neomake#GetMakeOptions more robust

- autoload/neomake/makers/ft/java.vim
I've noticed that invoking neomake#makers#ft#java#javac during tests
leaves temporary directories behind.
Using `tempname()` simplifies the code a lot, and will make (Neo)Vim
remove those automatically.
> java: use builtin tempname()

- autoload/neomake/makers/ft/typescript.vim
This will override the (not recommended) `watch: true` from the config.
Ref: https://github.com/neomake/neomake/issues/1203#issuecomment-301489908.
> typescript: tsc: add '--watch false' to args

- autoload/neomake/makers/ft/rst.vim
This allows to use e.g. `writegood` in ReST files after all.
For the real fix see https://github.com/neomake/neomake/issues/1314.
> rst: use 'text' as superset

- autoload/neomake/makers/ft/haskell.vim
Based on https://github.com/neomake/neomake/pull/1261.
> Fix haskell: hdevtools: empty output from stack

- autoload/neomake/makers/ft/go.vim
- tests/ft_go.vader
- tests/include/init.vim
- tests/neomake.vader
This was quite broken since a while at least already, and should not be
necessary anymore, at least since the 'errorformat' is evaluated in the
`cwd` (which picks up the names correctly).
Fixes https://github.com/neomake/neomake/issues/1306.
> Fix go makers: do not use mapexpr

- autoload/neomake/makers/ft/python.vim
Since mypy 0.510 there is no point to conditionally enable fast-parser - it is the only one available. Windows is supported by mypy.
```
λ mypy --no-fast-parser
Warning: --no-fast-parser no longer has any effect.  The fast parser is now mypy's default and only parser.
```
> Don't conditionally disable fast-parser for python mypy

- autoload/neomake.vim
- tests/lists.vader
Fixes https://github.com/neomake/neomake/issues/1097.
vim-qf's author said to have no bandwidth to merge / look at my PR (https://github.com/romainl/vim-qf/pull/48), so here is a workaround.
> Work around vim-qf messing via QuickFixCmdPost

- autoload/neomake.vim
- autoload/neomake/utils.vim
- tests/utils.vader
`b:neomake_exe` should not get picked up for maker settings.
> GetSetting/GetMaker: handle maker-only settings

- Makefile
This makes vimlint finish much faster usually.
> tests: run travis_lint against changed files only

- autoload/neomake/makers/ft/haskell.vim
This fix treats "--verbosity" and "silent" as independent tokens on the command line. 
The problem seems to have been introduced with https://github.com/neomake/neomake/commit/958b3c6f036a69a6cca71f198ae2565a6fcc9482 
@blueyed is probably the best person to review this.
Thanks!
> Fix stack command line options

- Makefile
Ref: https://github.com/syngan/vim-vimlint/issues/82#issuecomment-303883064.
> Makefile: vimlint: ignore _ as unused var by default

- autoload/neomake.vim
This makes it show up after typing/using `:Neomake` would have cleared
the cmdline, without having to trigger CursorMoved first.
> Echo current error when all jobs finished (forced)

- autoload/neomake.vim
- doc/neomake.txt
- plugin/neomake.vim
- tests/neomake.vader
- tests/toggle.vader
This is taken out of the "automake" branch, and `s:Make` uses
`expand('<abuf>')` to detect if it is invoked automatically (via an
autocommand), where the "disabled" setting is checked then.
> Add commands to toggle/disable/enable Neomake per buffer/tab/global

- tests/include/init.vim
- tests/include/setup.vader
Vim 7.3 will not include the "abort" attribute there, and the name is
unique anyway.
> tests: only use function name for check in teardown

- autoload/neomake/utils.vim
- tests/include/init.vim
- tests/utils.vader
Add a helper function to fix self-references in objects, and use it when
logging remaining jobs in tests.
This is required in case a maker stores the jobinfo object on `self`
etc.
> Add neomake#utils#fix_self_ref

- autoload/neomake/makers/ft/elm.vim
- tests/ft_elm.vader
Neomake complains about missing `bufnr` property in elm maker output. This request adds `bufnr` to error dictionary
> filename for elm maker output item

- autoload/neomake/makers/ft/objc.vim
The Objective-C maker is for the most part a copy of the C maker, except some parameters have been adjusted to be more sensible for the use with Objective-C. Fixes #453
> Add Objective-C maker

- autoload/neomake.vim
- tests/postprocess.vader
Otherwise it might interfere with `neomake#utils#hook`.
Still not documented, and better to replace it with a function arg after
all.
> postprocess: use g:neomake_postprocess_context

- tests/utils.vader
Patch 7.4.1644 was marked as "NA" before, but the behavior in this
regard remains different.
> tests: fix "neomake#utils#fix_self_ref" for Neovim being 8.0

- autoload/neomake/signs.vim
- tests/cwd.vader
- tests/integration.vader
- tests/signs.vader
- Use separate sign names ('neomake_file_err' and 'neomake_project_err',
instead of only 'neomake_err').
- Use just a single base sign_id.
> Fix sign handling across file/project mode

- autoload/neomake.vim
- autoload/neomake/compat.vim
Fixes https://github.com/neomake/neomake/issues/1476.
TODO:
> Add neomake#compat#get_argv to fix .cmd lookup on Windows

- autoload/neomake/compat.vim
- tests/compat.vader
- escape argv when wrapping it in a shell
- do not wrap it in a shell twice
Fixes https://github.com/neomake/neomake/issues/1481.
> Fix neomake#compat#get_argv for Windows

- .travis.yml
Using "none" still appears to (conditionally) call "bundle install"
(install.bundler step).
> Travis: language: generic

- autoload/neomake/makers/ft/cpp.vim
By default, gcc and clang default to the 2003 C++ version. Regardless of project make settings, I think it's a safe assumption for the default standard that neomake checks syntax against to be the latest supported standard (currently C++1z)
> Use latest supported version of C++ standard by default for cpp maker

- autoload/neomake/makers/ft/php.vim
Disables phpstan's progress output to not pollute the location list.
> [php.phpstan] Disable progress output

- tests/processing.vader
NVIM v0.2.1-642-g36a91c790 might also need more sleep (on Travis, see
https://travis-ci.org/neomake/neomake/jobs/261314821).
> tests: simplify sleep in postprocess test

- autoload/neomake/makers/ft/typescript.vim
Using --project would allow to use `--type-check` now, but only if a `tsconfig.json` file is found.
> tslint: do not append file twice, use --project

- autoload/neomake/makers/ft/python.vim
This flag makes mypy behave less surprisingly. A core part of mypy is
that it infers types and performs checks based on these inferences. With
this flag set, more code is covered.
>`--check-untyped-defs` is less severe than the previous option – it
> type checks the body of every function, regardless of whether it has
> type annotations. (By default the bodies of functions without
> annotations are not type checked.) It will assume all arguments have
> type Any and always infer Any as the return type.
http://mypy.readthedocs.io/en/latest/command_line.html
> Mypy: check untyped defs

- autoload/neomake/makers/ft/go.vim
Replaces 3 go linters by one. See [megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck).
> megacheck runs staticcheck, gosimple and unused

- autoload/neomake/utils.vim
- tests/ft_text.vader
- tests/signs.vader
- tests/utils.vader
Passing a list will not wrap it in a shell.
> neomake#utils#MakerFromCommand: set exe/args; support list

- autoload/neomake/makers/ft/scss.vim
sass-lint uses eslint under the hood, thus we can just use the same formatting that is used with js.
> Use eslint error format for sass-lint

- contrib/highlight-log
This avoids having the messages being displayed with Neovim.
> contrib/highlight-log: suppress output for --compact also

- autoload/neomake/makers/ft/java.vim
To make this works, we just need a task called `classpath` on the Ant
build.xml file, that returns the classpath needed to compile the current
file on Vim. It can be a fixed string or a command that returns a
combination of paths, like:
```
<?xml version="1.0"?>
<project name="neomake" default="build" basedir=".">
<path id="compile.path">
<pathelement location="a.jar"/>
<pathelement location="b.jar"/>
<pathelement location="c.jar"/>
</path>
<target name="classpath">
<echo message="${toString:compile.path}"/>
</target>
</project>
```
which will print:
```
$ ant classpath -f build.xml -S -q
/tmp/a.jar:/tmp/b.jar:/tmp/c.jar
```
that can be used on Neomake.
> Getting CLASSPATH from Apache Ant build file.

- autoload/neomake/makers/ft/python.vim
The '--ignore-missing-imports' switch is enough to ignore missing
imports, adding the skip breaks all annotations using imported types,
which isn't desireable in most use cases.
This is also more in line with the comment on replacing the old
--silent-imports with the new flags.
I have been testing this change with large Python code bases since
I opened the issue and have found mypy to work great.
> mypy: Remove '--follow-imports=skip' fixes #1528

- autoload/neomake/makers/ft/help.vim
- tests/ft_help.vader
It is really more meant for prose and not easy to configure regarding
its ignore lists etc.
> makers: help: do not use proselint by default

- autoload/neomake/makers/ft/markdown.vim
Followup to eac942fb - cutting down proselint usage, which is not easy
to configure and chokes on fenced code blocks etc.
> makers: markdown: do not use proselint by default

- autoload/neomake/makers/ft/c.vim
- autoload/neomake/makers/ft/cpp.vim
I've made some improvements to the C and C++ makers that should be safe to apply for everyone for single-file makers. The most important improvement is include -I./ in the arguments to the single-file makers for C/C++ for clang and gcc to include the current project directory in the header file search path. A lot of build systems generate a top-level config.h that is placed in that directory, regardless of where the rest of the source code actually lives.
Also, the clang-check and clang-tidy makers were broken for a couple of reasons. First, the clang arguments do not go directly to the clang-{check,tidy} tool, they have to be separated by a literal `--`, otherwise they are interpreted as arguments to the tool and not the compiler. Second, for some reason clang-check and clang-tidy were …
> C and C++ maker improvements

- autoload/neomake/makers/ft/sh.vim
so that the maker runs on nixos. Should be more universal.
> Use '/usr/bin/env sh' instead of '/bin/sh'

- autoload/neomake/config.vim
- autoload/neomake/debug.vim
Vim's :profile ignores the first line, so having documentation there
helps.
Ref: https://github.com/vim/vim/issues/2103
> minor: add doc headers to improve coverage

- autoload/neomake/makers/ft/python.vim
There is nothing expensive there (anymore), and it should pick up new
executables.
> python: do not cache return value from EnabledMakers

- Makefile
- tests/vim/vimrc
This reverts commit 3086c9704ec50bce1a0366a92a6a0d1ff88f7095.
It breaks e.g.
> make docker_test TEST_VIM=vim73 VADER_ARGS=tests/signs.vader VADER_OPTIONS=-x
> Revert "Makefile: _docker_test: do not push down VADER_ARGS forcefully (#1609)"

- .travis.yml
- Makefile
Linting/check errors should not cause coverage drops.
> Travis: move "make check" (without new docker_check) to lint

- autoload/neomake.vim
- autoload/neomake/compat.vim
- autoload/neomake/configure.vim
- tests/compat.vader
- tests/include/init.vim
- tests/processing.vader
This is only relevant for Vim, and cannot be tested in Neovim even.
Ref: https://github.com/neovim/neovim/issues/7350
> Do not process output/lists in operator-pending mode (Vim)

- README.md
The TravisCI badge seems outdated. Now we have the choice between:
and
The PR uses the latter, since it better fits with other badges out there.
> README: use CircleCI badge

- autoload/neomake/makers/ft/tex.vim
The '-shell-escape' argument is needed by some latex packages (e.g. minted).
Without it, pdflatex will notify the user about errors that aren't actually
present in the document.
> Add '-shell-escape' argument to pdflatex maker.

- autoload/neomake.vim
This was never really working recently anyway.  It should get done
through other methods if you need this.
> _get_argv: drop support for handling dynamic exe

- tests/include/init.vim
- tests/isolated.vader
- tests/isolated/modes.vader
- tests/processing.vader
The new monkeypatch method (NeomakeTestsMonkeyPatch) does not work
really: where re-sourcing the function through the temporary file, it
does not appear in the :profile output at all anymore.
> tests: add tests/isolated/modes.vader

- autoload/neomake/makers/ft/verilog.vim
Fix an error caused by an extra space and make it possible to build files with locally defined external modules
> Verilog fixes

- autoload/neomake.vim
- doc/neomake.txt
- tests/lists.vader
This will take into account the number of list entries (e.g. 3) when
creating a location list or quickfix window, and uses the minimum of
`g:neomake_list_height` and that.
Therefore with only 3 entries it will use 3 instead of 10 now by
default.
It is still a good idea to use something like
https://github.com/blueyed/vim-qf_resize in general, but this improves
the default behavior.
> loclist/qflist: use number of entries for window height

- .circleci/config.yml
This reverts commit 3468a63116bc5b5ec766c23af991c55c67bb94cd.
Codecov currently does not handle coverage uploads for merge commits
properly.
This keeps it for the "checkqa" build.
> Revert "CircleCI: test merge commit (#1673)"

- autoload/neomake.vim
- autoload/neomake/configure.vim
- autoload/neomake/core.vim
- tests/automake.vader
This factors out `neomake#core#create_jobs` and uses it to create the
list of jobs for automaking only once.
This causes checks to happen earlier (which is good).
The `cwd` handling is kept out, since a buffer's name (and therefore a
`cwd` based on it) can change.
> Pre-create maker_jobs for automaking

- autoload/neomake/makers/clippy.vim
Ref: https://github.com/neomake/neomake/issues/1453
> clippy: use warning instead of error about nightly rust installation

- autoload/neomake/makers/ft/perl.vim
Align the perl error format more closely with the one provided by `:compiler perl`.
> improve perl errorformat

- autoload/neomake/makers/ft/solidity.vim
Adds a new checker for Solidity.
[Solhint](https://github.com/protofire/solhint) uses ESLint's formatters, so I've just reused them here.
Let me know if anything else needs to be added!
> Add Solhint checker

- autoload/neomake/makers/ft/perl.vim
- tests/ft_perl.vader
This prevents a stray extra space from appearing in the error message.
> only concat extramsg if nonempty

- autoload/neomake/makers/ft/zsh.vim
It isn't a superset of sh, it is a different shell
Also shellcheck does not have a --shell=zsh (anymore? since 2015 https://github.com/koalaman/shellcheck/blob/102683ab04bcb8a0a6f5d492e70fc8d3703edcc1/ShellCheck/Parser.hs#L2800-L2809)
https://github.com/koalaman/shellcheck/issues/809
being a superset enables shellcheck by default
todo:
> Undo 712c3ac zsh>sh + shellcheck

- autoload/neomake.vim
- tests/filter_output.vader
- tests/main.vader
This allows for filtering output in general, and allows for pylint to
filter away the "No config file found, using default configuration"
message on stderr, without having to use output_stream=both.
> Add filter_output setting/maker method

- autoload/neomake.vim
> HACK: keep refs for postprocess functions to show up in profiles

- autoload/neomake.vim
- tests/processing.vader
They should not get cleaned especially, since this might still happen
later in the exit handler.
> neomake#CancelJob: handle already exited jobs

- autoload/neomake/statusline.vim
- tests/processing.vader
With the same buffer opened in two windows, the non-current one might
have an "unknown" status, just because Neovim would have redrawn the
statusline too early.
> statusline: fix/improve call to redrawstatus

- autoload/neomake/makers/ft/javascript.vim
- tests/ft_javascript.vader
Ref: https://github.com/neomake/neomake/issues/1730
Might work around #1730 - so I would like to merge it only after it is clear what happens there.
> js: flow: ignore No-errors msg in errorformat

- autoload/neomake.vim
- tests/config.vader
Only use 'name' with maker passed to `neomake#utils#GetSetting`, so that
checking the new-style config (that is used with automaking) will not
use the default from the maker.
Fixes https://github.com/neomake/neomake/issues/1616.
> neomake#GetMaker: fix overriding config

- autoload/neomake/utils.vim
It is not clear to me why this would be needed (there is also no failing test),
and it pollutes `:verb set isk?`, because Neomake will show up there
then.
@tweekmonster 
What is the reason for using it in the first place?
Was `\k` being used initially or something like that?
> neomake#utils#ExpandArgs: do not change 'iskeyword'

- autoload/neomake.vim
- tests/hooks.vader
This was the jobinfo of the last job (already provided with
`NeomakeJobFinished`).
Instead the make info would be interesting, which can be retrieved via
`make_id` and `neomake#GetStatus().make_info` if needed.
> NeomakeFinished: remove jobinfo from hook context

- autoload/neomake/utils.vim
- tests/utils.vader
> neomake#utils#MakerFromCommand: remove _exe_wrapped_in_shell

- autoload/neomake/compat.vim
- tests/compat.vader
`empty(v:none)` is 1, and the same should be given for
`neomake#compat#json_none`.
> Change neomake#compat#json_none for `empty()`

- autoload/neomake/makers/ft/python.vim
- tests/ft_python.vader
Fixes https://github.com/neomake/neomake/issues/1806.
Closes https://github.com/neomake/neomake/pull/1808.
> python: pylint: ignore "Using config file" output

- autoload/neomake/makers/ft/json.vim
I don't know if this is something useful for others or not:
I wanted to use eslint for my json files. Maker definitions copied from `autoload/neomake/makers/ft/javascript.vim/javascript.vim` but adding `--plugin json` to `args`.
> Add eslint maker for .json

- autoload/neomake/makers/ft/rust.vim
- tests/ft_rust.vader
This is required due to recent changes.
Fixes https://github.com/neomake/neomake/issues/1809.
> rust: cargo: use dir with Cargo.toml as cwd

- autoload/neomake/utils.vim
- tests/cmd_neomakeinfo.vader
Otherwise `:verbose NeomakeInfo` would display a message for a filetype
without any makers (e.g. startify).
> Make :runtime for ft makers silent

- autoload/neomake.vim
- tests/processing.vader
Fixes https://github.com/neomake/neomake/issues/1816.
> nvim: fix buffered output with Neovim 0.2.2 reporting as 0.2.3

- autoload/neomake.vim
- tests/makers.vader
If `neomake#GetMaker` is used for non-file_mode it should not create a
maker with `append_file = 1`.
> neomake#GetMaker: do not set append_file

- autoload/neomake/highlights.vim
- doc/neomake.txt
- tests/highlights.vader
This is what Syntastic and ALE are using.
Fixes https://github.com/neomake/neomake/issues/1463.
Fixes https://github.com/neomake/neomake/issues/1662.
> highlights: link to SpellBad/SpellCap

- autoload/neomake/makers/ft/asciidoc.vim
Otherwise it creates `*.html` files next to the linted file(s).
> asciidoc: use /dev/null for output file

- autoload/neomake/statusline.vim
If the input string is empty, the output includes some detritus like `-q`.
> Fix statusline formatting with empty string

- autoload/neomake/makers/ft/python.vim
- autoload/neomake/postprocess.vim
- tests/ft_python.vader
- tests/postprocess.vader
"F821 undefined name 'bar'" with `f'foo bar'` refers to the beginning of
the f-string, and therefore the entry's `length` property should not be
set.
This changes the flake8 postprocessing to use the generic length
postprocessor, which results in no `length` attribute for this entry
(since it checks if the text is there).
A proper fix would be to search for the next `{bar}`, and adjust the
lnum/col also.
> python: flake8: fix length processing in f-strings

- tests/processing.vader
This was flaky on vim8069 (https://circleci.com/gh/neomake/neomake/6444).
> tests: improve "Output is not processed with visible popup menu"

- autoload/neomake/makers/ft/go.vim
- tests/ft_go.vader
Without this additional format, results from some linters (like [gas](https://github.com/GoASTScanner/gas)) are ignored
> Add additional errorrformat for gometalinter

- autoload/neomake/utils.vim
- tests/utils.vader
This skips escaping of `--foo=bar`, which is used often.
> neomake#utils#shellescape: do not quote =

- autoload/neomake.vim
We might want to skip this altogether, but for now it should be silent
already.
Fixes https://github.com/neomake/neomake/issues/1876
> Make :bwipeout silent with &report < 2

- autoload/neomake.vim
- autoload/neomake/compat.vim
- autoload/neomake/debug.vim
- doc/neomake.txt
- tests/compat.vader
- tests/debug.vader
- tests/main.vader
- tests/makers.vader
Fixes https://github.com/neomake/neomake/issues/1795
TODO:
~~- [ ] should use a more pipe-aware approach, i.e. if both `process_output` and `process_json` are there, `process_output` should be called first - allowing to fix the output for the internal `process_json` wrapper.~~ (there is filter_output already)
> Add process_json output handler

- autoload/neomake/makers/ft/ruby.vim
Github Issue: https://github.com/neomake/neomake/issues/1886
Rubocop frequently updates their `.rubocop.yml` syntax, which is annoying. This cascades into silent failures when running `:Neomake` because neomake is trying to process the output from `stderr`.
> Specify stdout as the output stream for rubocop & rubocop_rails.

- autoload/neomake/makers/ft/swift.vim
Previously the only Swift maker was just for compiling a single file
with no arguments, now if there is a Package.swift file in the current
directory, we will use `swift build` instead.
> Add Swift package manager support

- tests/isolated/compat-get_argv-on-emulated-windows.vader
Do not restore, which removes existing coverage info.
> tests: fix tests/isolated/compat-get_argv-on-emulated-windows.vader

- autoload/neomake.vim
Fixes https://github.com/neomake/neomake/issues/1216 for unix-likes.
> neovim: jobstart: use detach=1 with Neovim before 0.2.3

- autoload/neomake/makers/ft/asciidoc.vim
asciidoc is EOL (final release), and recommends using asciidoctor
instead: https://github.com/asciidoc/asciidoc/releases/tag/8.6.10.
> asciidoc: prefer asciidoctor over asciidoc

- autoload/neomake/quickfix.vim
- tests/customqf.vader
Those are typically informational messages, and having those trigger
displaying of bufnames in general (if there is only a single buffer
otherwise), and the "buf:0" itself is not helpful.
> customqf: do not display buf:0 with buffer=0 msgs

- autoload/neomake/makers/ft/cpp.vim
Do not pass options after `--`.
Fixes https://github.com/neomake/neomake/issues/1596.
> cpp: fix clangtidy/clangcheck

- autoload/neomake/configure.vim
- tests/automake.vader
This cancels running makes as soon as the timer gets started, because
the existing make run is outdated then already.
> automake: cancel running makes early

- autoload/neomake/log.vim
- tests/isolated/logging.vader
- tests/log.vader
This was changed in 5d46a240 recently, and now works again like before.
> logging: do not include context information always

- autoload/neomake/compat.vim
- autoload/neomake/makers/ft/erlang.vim
- tests/compat.vader
- tests/ft_erlang.vader
- tests/main.vader
This maker does an educated guess about where `include` and `ebin` directories might be. It tries standard Rebar 3 paths, but also allows to set `g:erlang_extra_deps` to provide a custom file location. ~It uses relative paths, as it assumes that Vim is run in the project's directory and CWD is not changed to the file-being-edited location.~
It heavily follows the 80/20 rule, so the most common false errors in the majority of straightforward Rebar3 (and possibly old Rebar2) projects should be covered, but there are no guarantees. Still, it's way better than running `erlc` with no command line params at all.
It's my first 30 lines of VimScript, so I beg for mercy :)
> Define an Erlang maker aware of header and code path locations

- autoload/neomake/makers/ft/go.vim
without this option, gometalinter output will be crazy, so ignoring vendor directories is definitely preferable to most golang users.
https://github.com/alecthomas/gometalinter/issues/344
> exclude vendor directories when running gometalinter

- autoload/neomake.vim
Fixes https://github.com/neomake/neomake/issues/1955.
> neovim: Windows: do not use `detach` by default

- tests/cancellation.vader
Use `string()` for Vim job, so that it matches the log message better.
> tests: fix flakyness with neomake#CancelJob

- .circleci/config.yml
- Dockerfile.tests
- Makefile
- tests/customqf.vader
- tests/cwd.vader
- tests/ft_asciidoc.vader
- tests/ft_cs.vader
- tests/ft_css.vader
- tests/ft_go.vader
- tests/ft_javascript.vader
- tests/ft_python.vader
- tests/ft_rst.vader
- tests/ft_sh.vader
- tests/ft_text.vader
- tests/ft_typescript.vader
- tests/ft_vim.vader
- tests/ft_xml.vader
- tests/include/init.vim
- tests/integration.vader
- tests/isolated/highlights.vader
- tests/makers.vader
- tests/postprocess.vader
- tests/processing.vader
- tests/signs.vader
- tests/tempfiles.vader
> tests: bump Docker image

- Makefile
- tests/vim/vimrc
Fixes https://github.com/neovim/neovim/commit/8fa0b8051dbe2f4e4a00c162913886a34bf78bfa#commitcomment-28909322.
> tests: set NVIM_LOG_FILE in environment instead of vimrc

- plugin/neomake.vim
- tests/toggle.vader
Fixes:
> Vim(autocmd):E216: No such group or event: neomake
Ref: https://github.com/neomake/neomake/issues/1969.
> NeomakeDisable: do not try to delete non-existing augroup

- autoload/neomake/makers/ft/swift.vim
This new maker is ever on by default, but allows people to easily test
their SwiftPM projects if they enable it.
> Add SwiftPM test maker

- autoload/neomake.vim
This does not really seem to matter, but makes it more consistent.
> s:ProcessEntries: create list after cd

- autoload/neomake/makers/ft/swift.vim
This command can produce normal errors with a column, but also those
without, so we need both formats.
> Add SwiftPM errorformat

- .circleci/config.yml
- Dockerfile.tests
- Makefile
- autoload/neomake.vim
- tests/env.vader
Related patches:
- 8.0.1832: https://github.com/vim/vim/commit/137374fd6538cf9dee0cb22907728d8fdecb5832
- 8.0.0902: https://github.com/vim/vim/commit/05aafed54b50b602315ae55d83a7d089804cecb0
> Unlet $NEOMAKE_FILE / use jobopts.env with existing Vim patches

- autoload/neomake/makers/ft/vim.vim
- tests/isolated.vader
- tests/isolated/ft_vim.vader
Requires vint 0.4a1+.  It was added partly in 0.3.19 already, but that
is buggy.
> vim: vint: detect new stdin support

- autoload/neomake/makers/clippy.vim
- tests/include/init.vim
- tests/vim/vimrc
Adds g:neomake_clippy_rustup_has_nightly to allow for skipping clippy's
check (using system()!).
Ref: https://github.com/neomake/neomake/issues/1453
> tests: look for unexpected warnings

- autoload/neomake/makers/ft/javascript.vim
- tests/filetypes.vader
typescript compiler can run in javascript project or files when is configured with "allowjs" and "checkjs" in tsconfig.json
> enable typescript compiler to javascript files

- Makefile
- autoload/neomake.vim
- autoload/neomake/core.vim
- autoload/neomake/makers/ft/haskell.vim
- autoload/neomake/makers/ft/java.vim
- autoload/neomake/makers/ft/javascript.vim
- autoload/neomake/makers/ft/vim.vim
- autoload/neomake/utils.vim
Via https://github.com/syngan/vim-vimlint/issues/101#issuecomment-402725362.
> vimlint: use -e 'EVL103.a:_.*=1' to ignore unused args

- tests/integration.vader
Fixes flakiness in Vim.
Ref: https://circleci.com/gh/neomake/neomake/11422
> tests: harden "Location list should be cleared only after first output"

- contrib/highlight-log
It might be after some output from ":echom" when quiet mode is used.
Ref: https://github.com/junegunn/vader.vim/pull/172
> contrib/highlight-log: match "Starting Vader:" everywhere

- .circleci/config.yml
- .coveragerc
- Dockerfile.tests
- Makefile
`.coverage.covimerage` gets picked up by coveragepy when combining data,
which gets triggered through pytest-cov.
> tests: coverage: use data_file=.coverage_covimerage

- autoload/neomake.vim
- autoload/neomake/utils.vim
- tests/hooks-queue.vader
This fixes a missing-make_info error in case an outer NeomakeJobFinished
hook invocation wraps the one from the following job.
> Handle nested hook invocations via action queue

- autoload/neomake/compat.vim
- autoload/neomake/makers/ft/markdown.vim
- tests/compat.vader
- tests/ft_markdown.vader
- tests/main.vader
- tests/makers.vader
Request input particularly on the `let filename = buffer_name(bufnr)` line -- that can't be the best way to go through the JSON object...
> add vale linting (process_json)

- .circleci/config.yml
- Dockerfile.tests
- Makefile
- tests/cwd.vader
vim-master appears to segfault because of https://github.com/vim/vim/commit/ad6480961080f80a455b2394f27b02935a2ded52#commitcomment-29794285.
> Docker/tests: add nvim 0.3.1, remove others

- autoload/neomake/makers/ft/swift.vim
Previously building only meant building source modules. Now it also
builds tests to find compiler errors.
We might not want to make this the default, since some people might not expect this behavior. Alternatively we could expose a setting that allows users to pass more arguments to `swift build` if they'd like to.
> Make SwiftPM build tests

- autoload/neomake.vim
- doc/neomake.txt
- tests/include/init.vim
- tests/stdin.vader
`uses_stdin` can be set on the maker or via settings unconditionally.
> Add support for always using stdin

- autoload/neomake.vim
- tests/list-entries.vader
- tests/main.vader
- tests/makers.vader
This is important for e.g. using makeprg=make, which typically has a lot
of invalid/unrecognized entries.
> Only use default_entry_type for valid entries

- autoload/neomake/configure.vim
- tests/automake.vader
Also take the window into account for the position.
It might make sense to retrigger (i.e. not forget about) events like
"TextChanged", "BufWritePost" in general though (as long as the tick matches).
> automake: do not restart timers in general if pos changed

- autoload/neomake/makers/ft/php.vim
particularly when no errors found, phpcs would output it's progress unnecessary polluting location list
> [php.phpcs] disable phpcs progress

- Makefile
- autoload/neomake.vim
- autoload/neomake/action_queue.vim
- autoload/neomake/utils.vim
- contrib/highlight-log
- tests/cancellation.vader
- tests/cwd.vader
- tests/hooks-queue.vader
- tests/include/init.vim
- tests/integration.vader
- tests/isolated/highlights.vader
- tests/lists.vader
- tests/makers.vader
- tests/processing.vader
TODO:
- ~~[ ] fix coverage for s:function (https://codecov.io/gh/neomake/neomake/compare/9423dc2a8a3999d138f3a4cd8bdfc2750d1087d8...9ffd3376526feccc392e22a033e1de612d8035be/diff#D9-58). Needs https://github.com/vim/vim/pull/3362 and covimerage using it.~~  Postponing.
> Factor out action queue processing

- autoload/neomake.vim
- doc/neomake.txt
- tests/cwd.vader
- tests/mapexpr.vader
Relevant for cargo (ref https://github.com/rust-lang/rust.vim/pull/261).
> process_output/mapexpr: use job's cwd

- autoload/neomake/jobinfo.vim
- autoload/neomake/makers/ft/rust.vim
- autoload/neomake/utils.vim
- tests/ft_rust.vader
- tests/utils.vader
Includes https://github.com/neomake/neomake/pull/2082.
/cc @dpc
> rust: cargo: use workspace_root from metadata

- autoload/neomake/makers/ft/markdown.vim
It appears to mark the start and end column, so 1 needs to be added.
> markdown: vale: fix off-by-one error with length

- autoload/neomake.vim
I'm coming from using dispatch and vim-rspec where the quickfix window was always opened using botright and i find it a bit weird how neomake opens lwindow and cwindow.
This PR serves more as a question to you @blueyed. I don't actually know what `cwindow` defaults to? From my testing it seem to open under the rightmost split?
You might be more open to putting this behind a config flag instead of hardcoding it to botright?
> Open cwindow botright

- autoload/neomake/compat.vim
- tests/processing.vader
This avoids internal action queue processing for WinEnter when a
location list window has been opened.
> neomake#compat#restore_prev_windows: use noautocmd

- autoload/neomake.vim
- autoload/neomake/makers/ft/bib.vim
- autoload/neomake/makers/ft/c.vim
- autoload/neomake/makers/ft/cf3.vim
- autoload/neomake/makers/ft/javascript.vim
- autoload/neomake/makers/ft/moon.vim
- autoload/neomake/makers/ft/nix.vim
- autoload/neomake/makers/ft/objc.vim
- autoload/neomake/makers/ft/php.vim
- autoload/neomake/makers/ft/r.vim
- autoload/neomake/makers/ft/rust.vim
- autoload/neomake/utils.vim
- doc/neomake.txt
- tests/tempfiles.vader
- tests/utils.vader
This fixes the filename being passed twice to clangtidy etc, and behaves
as documented now.
> Fix args/append_file for various makers

- autoload/neomake/configure.vim
Neovim development version does have patch-8.0.1633, but does not report
it yet.
> Check for `nvim-0.3.2` with "Ignoring first TextChanged"

- tests/compat.vader
Use `--headless` to not make `--embed` wait for UI.
> tests: fix "neomake#compat#get_mode" for Neovim dev

- autoload/neomake.vim
- tests/errors.vader
- tests/tempfiles.vader
Also improves log context (adding job info) for generic Neomake errors.
> skip_job: require msg/reason

- autoload/neomake/makers/ft/c.vim
- autoload/neomake/makers/ft/cpp.vim
@miedzinski 
Does this make sense?
I also wonder if `cppcheck` adds anything over `clang-check` (if both are available)?
I've noticed that it is more picky when using e.g. `%d` for unsigned ints in `printf`.
I plan to only enable `clang-check` (fast) by default, if there is a compilation database (`compile_commands.json`), and then `cppcheck` would not be enabled by default.
TODO:
> c: cppcheck: use custom template for columns

- autoload/neomake/makers/ft/php.vim
The latest version of phpstan has marked the --errorFormat parameter as deprecated and recommend --error-format instead.
> php: change phpstan's --errorFormat to --error-format

- autoload/neomake/makers/ft/proto.vim
This adds a Protocol Buffers (*.proto) maker and introduces Uber's prototool as the default maker.
> [proto.prototool] Add proto maker

- autoload/neomake/makers/ft/markdown.vim
It is distracting, e.g. with '"only" can weaken meaning'.
> markdown: do not enable writegood by default

- autoload/neomake.vim
- tests/cmd_neomakeinfo.vader
- tests/lists.vader
Check if any `QuickfixCmdPost` autocommand exists before triggering it
delayed.
> Do not trigger "No matching autocommands" messages

- autoload/neomake.vim
- autoload/neomake/compat.vim
- autoload/neomake/core.vim
- autoload/neomake/list.vim
- plugin/neomake.vim
- tests/customqf.vader
- tests/cwd.vader
- tests/ft_javascript.vader
- tests/integration.vader
- tests/isolated/highlights.vader
- tests/list.vader
- tests/lists.vader
- tests/main.vader
- tests/makers.vader
- tests/processing.vader
- tests/signs.vader
- tests/tempfiles.vader
This adds new commands to go to the next/prev entry (relative to the cursor by default):
NeomakeNextLoclist/NeomakePrevLoclist and NeomakeNextQuickfix/NeomakePrevQuickfix
Integrates with vim-unimpaired via https://github.com/tpope/vim-unimpaired/pull/146.
> Improve / factor out (quickfix/location) list processing

- autoload/neomake.vim
- doc/neomake.txt
- tests/stdin.vader
This is useful for e.g. vint to skip the version check.
> supports_stdin can be a setting

- autoload/neomake/log.vim
- tests/automake.vader
- tests/include/init.vim
- tests/integration.vader
Do not require to pass whole context with asserting messages.
> tests/logging: add winnr to context

- autoload/neomake.vim
- autoload/neomake/list.vim
Do not set an empty list initially, but only with new/first entries, or
when make is finished.
> automake: prevent qf list flickering

- autoload/neomake.vim
- tests/automake.vader
Ref: https://github.com/neomake/neomake/issues/2201.
> s:CleanJobinfo: log when not cleaning make info

- autoload/neomake/list.vim
This fixes flickering with the custom quickfix formatting (customqf), where otherwise signs are removed and replaced unnecessarily otherwise.
> list: use "noautocmd" with init-qf-for-lwindow workaround

- autoload/neomake/list.vim
- tests/list.vader
Still enabled by default with a logfile, but might be too verbose.
> Use g:neomake_debug_list to control list debugging

- autoload/neomake.vim
- tests/lists.vader
This also get enabled when all jobs/makers use it.
It currently does not use settings, and therefore has to be used
explicitly, e.g. via `call neomake#Make({'use_list': 0, …})`, or by
setting it in a custom maker object directly (and only using makers with
`use_list=0`).
> Add "use_list" make option

- autoload/neomake/configure.vim
- tests/automake.vader
This is needed to work around some Vim bug, where TextChanged is
triggered still when defined after/during BufWritePost handling.
> automake: restart: compare tick

- autoload/neomake/makers/ft/vim.vim
It should only look at (versioned) files in (autoload|plugin)/, but is
not really worth it in general.
> vim: do not enable neomake_checks by default

- autoload/neomake/configure.vim
- tests/automake.vader
- check workaround first
- do not emit warning - with a long running maker this would only be
confusing after all.  We cannot really warn about a bad setup (e.g.
some autoformatter run on BufWritePost after Neomake) reliably/easily.
> automake: restart: cleanup

- tests/log.vader
Might take longer than 10ms (on CI):
> [D +0.19]: [-.-:-:1] msg4.
(319/654) [EXECUTE] (X) Message does not match: 18:31:44 85 [D +0.19] [-.-:-:1] msg4.
> tests/log.vader: losen delay

- autoload/neomake/makers/ft/ada.vim
The -gnats flag only checks syntax which misses quite a few cases that
will result in a build failure.
> ada: use gnatc to check both syntax and semantics

- autoload/neomake/utils.vim
- tests/tempfiles.vader
This patch sets the file permissions on temporary files to 0644, which I presume was the intention because there was a test testing this. I'm not sure if it is necessary to check if setfperm exists. It seems like it was added to vim quite recently, in 2016: https://github.com/vim/vim/commit/8049253b96838b3584600e5ad229abad37a95b10
fixes #2293
> Set permissions on temporary files

- tests/cwd.vader
Fixes https://github.com/neomake/neomake/issues/2292.
> tests: fix "tempfile with pwd" when run from symlinked dir

- autoload/neomake/makers/ft/typescript.vim
- tests/ft_typescript.vader
Fixes https://github.com/neomake/neomake/pull/2307.
> typescript: tslint: handle new errorformat with 5.12.0

- .circleci/config.yml
Those appear to trigger timeouts with Codecov's backend.  Use env vars
instead.
> ci: codecov: do not use flags

- autoload/neomake/signs.vim
- autoload/neomake/utils.vim
- tests/include/init.vim
- tests/isolated.vader
- tests/isolated/sign-highlights.vader
Fallback to "Normal" highlight if there is no background for
"SignColumn".
Fixes https://github.com/neomake/neomake/pull/2316.
TODO:
> signs: fix/improve neomake#signs#DefineHighlights

- autoload/neomake.vim
- autoload/neomake/configure.vim
- tests/automake.vader
- b:_neomake_automake_make_ids
- b:_neomake_automake_tick
This way they will not show up with `b:neomake_<tab>`.
> Add underscore to private automake buffer vars

- autoload/neomake/makers/ft/go.vim
- tests/ft_go.vader
When there are no test files, go command prints an output line similar to:
```
?   	github.com/cenkalti/rain/rainrpc	[no test files]
```
This line does not need to be visible on location list. This PR makes a change to hide that line.
> hide [no test files] line for go maker

- autoload/neomake.vim
This is used with the experimental neomake#_handle_list_display wrapper,
which I am using myself, and it should not ignore
`b:neomake_open_list = 0`.
> s:HandleLoclistQflistDisplay: handle a:1 as default

- autoload/neomake/makers/ft/typescript.vim
eslint can now be used for typescript aswell, see: https://github.com/typescript-eslint/typescript-eslint
> Add eslint to typescript markers

- autoload/neomake/makers/ft/php.vim
- tests/ft_php.vader
Before this change, all psalm-generated messages where of "Error" type.
Now the error type is correctly determined/parsed from the output message.
> php: Correctly display psalm error type

- tests/signs.vader
This is meant to be more robust in case signs are not two chars long.
(https://github.com/neovim/neovim/pull/9788)
> tests: neomake#signs#RedefineErrorSign: split sign

- autoload/neomake/utils.vim
- tests/utils.vader
#895 fixed that a character was cut in the middle, but it may still be too long.
> fix echo messages too long when there are double width characters

- autoload/neomake/signs.vim
'DOUBLE EXCLAMATION MARK' (U+203C) is typically more visible than
'WARNING SIGN' (U+26A0), which would require the emoji variation
selector (U+fe0f) to render it in width 2, but that makes it wider than
the other defaults, and is not handled well in Neovim/Vim.
Ref: https://github.com/kovidgoyal/kitty/issues/1612
Ref: https://github.com/neovim/neovim/issues/7151
> signs: change default for warning sign to "‼"

- contrib/highlight-log
Also display everything before "Starting Vader" already.
Quiet mode was meant to suppress the version output (handled via `-q`
with Vader), and any messages during test collection/parsing, which are
not there anymore, and therefore also do not trigger the (removed)
spinner anymore.
> contrib/highlight: remove support for quiet mode

- autoload/neomake/utils.vim
- tests/isolated/sign-highlights.vader
Use the correct/explicit mode when testing for "reverse".
> neomake#utils#GetHighlight: use mode with reverse

- autoload/neomake.vim
- autoload/neomake/config.vim
- autoload/neomake/core.vim
- autoload/neomake/debug.vim
- autoload/neomake/list.vim
- autoload/neomake/utils.vim
- contrib/vim-checks
- tests/utils.vader
Would cause the following error with an existing function `F`:
> E705: Variable name conflicts with existing function: F.
> Use l: prefix with uppercase variable names (for possible function assignment)

- tests/compat.vader
- tests/stdin.vader
Ref: https://github.com/neovim/neovim/issues/10031#issuecomment-493755631
With `--embed` it would hang with output during autoload, likely waiting
for an hit-enter prompt (e.g. with `for i in range(0, 10) | echom i | endfor`
in `autoload/neomake/highlights.vim`).
TODO:
> tests: do not use --embed with nvim in RPC based test

- autoload/neomake.vim
- autoload/neomake/debug.vim
- autoload/neomake/jobinfo.vim
- tests/include/init.vim
- tests/jobinfo.vader
This adds `file_mode` and `bufnr` there by default now.
> Use neomake#jobinfo#new() for jobinfo objects

- autoload/neomake/configure.vim
- tests/automake.vader
- tests/main.vader
- tests/vim_and_neovim_behavior.vader
Due to https://github.com/vim/vim/issues/2764.
> automake: remove BufWritePost/changedtick workaround

- autoload/neomake/makers/ft/rust.vim
- tests/ft_rust.vader
Also use str2nr to have "nr" 61 for "0061", and not 49.
Fixes https://github.com/neomake/neomake/issues/1919.
> rust: cargo: fix type for entries with code

- autoload/neomake.vim
- autoload/neomake/cmd.vim
- autoload/neomake/virtualtext.vim
Previously it would still display the error, but not clear it with
`:NeomakeDisable`.
Needs to be improved, but appears to be a good quick fix.
Ref: https://github.com/neomake/neomake/issues/2390
> Improve behavior of virtualtext after disabling

- autoload/neomake.vim
- tests/makers.vader
This can be useful when setting `b:neomake_X_enabled_makers` manually,
but not wanting to see errors with missing executables.
> makers: keep auto_enabled value if explicitly set

- autoload/neomake/makers/ft/ruby.vim
I was annoyed by RuboCop complaining about the temporary filename chosen by Neomake. (RuboCop includes a linter for the filenames as well.)
Adding support for stdin fixes this.
> Add stdin support for RuboCop

- autoload/neomake/utils.vim
- tests/automake.vader
- tests/hooks-queue.vader
- tests/hooks.vader
- tests/processing.vader
This makes `:verbose Neomake …` more useful (in case you have hooks
defined - those are not useful to see there then).
> logging: use debug level for hook messages

- autoload/neomake/makers/ft/go.vim
The long line linter doesn't include a column in the error output:
```
$ golangci-lint run --disable-all --enable=lll --out-format=line-number --print-issued-lines=false main.go
main.go:216: line is 124 characters (lll)
main.go:217: line is 124 characters (lll)
main.go:220: line is 124 characters (lll)
main.go:235: line is 122 characters (lll)
main.go:237: line is 134 characters (lll)
main.go:238: line is 128 characters (lll)
main.go:269: line is 122 characters (lll)
main.go:420: line is 148 characters (lll)
```
This commit adds an errorformat that matches lint output missing column information.
> Updates golangci_lint error formats for lll

- autoload/neomake/makers/ft/c.vim
This might result in a lot of runs with e.g. Vim's source.
It is better to limit this to the default then (12), displaying an
information then.  User's should configure it then to their liking
instead (using custom args).
> c/cpp: cppcheck: do not use "--force"

- autoload/neomake/utils.vim
> neomake#utils#WideMessage: use v:echospace

- autoload/neomake.vim
- tests/include/init.vim
- tests/processing.vader
Instantiated makers might be different from the new/uninstantiated ones,
e.g. with regard to args or `tempfile_name` etc.
> Only compare maker name when canceling already running jobs

- tests/fixtures/errors.py
- tests/ft_python.vader
The location there changed.  This updates the test to use python2 for
now.
> tests: fix "python: errorformat" for py38+

- autoload/neomake/makers/ft/markdown.vim
The format of markdownlint-cli seems to have changed at 0.19.0.
```sh
$  echo 'test line' > 0.md
$ npm -g markdownlint-cli@0.18.0
$  markdownlint 0.md
0.md: 1: MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "test line"]
$ npm -g markdownlint-cli@0.19.0
$ markdownlint 0.md
0.md:1 MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "test line"]
```
> Fix errorformat for markdownlint-cli 0.19.0 or newer

- autoload/neomake/statusline.vim
- tests/statusline.vader
Neomake currently overrides any user provided `NeomakeStatColorType*` highlight configuration. 
This PR should fix that.
1. Add the following to .vimrc that already has neomake configured:
```vim
hi NeomakeStatColorTypeW  ctermfg=White  ctermbg=Blue  cterm=none
function! MyStatusLine()
let bufnr = winbufnr(g:statusline_winid)
let st = ""
let st .= "%< %-f  " " File path (truncated if necessary)
let st .= "%m%r%w %="
let st .= " %=" " Separation point
let st = neomake#statusline#get(bufnr, {
\ 'format_running': '({{running_job_names}}) ',
\ 'format_loclist_unknown': '',
\ 'format_loclist_ok': '✓',
\ 'format_quickfix_ok': '',
\ 'format_quickfix_issues': '%s',
\ })
return st
endfunction
set statusline=%!MyStatusLine()
```
2. Open a file with which neomake has a maker for, that contains a …
> fix: Define highlights as defaults to avoid overriding user config

- autoload/neomake/makers/ft/python.vim
- autoload/neomake/makers/ft/python/compile.py
E.g. '"is" with a literal. Did you mean "=="?"' with `assert 1 is 2`.
> python: handle SyntaxWarnings

- doc/neomake.txt
Taken out of https://github.com/neomake/neomake/pull/2474.
Vimhelplint added a new check in https://github.com/machakann/vim-vimhelplint/pull/9.
> Fix misc errors in doc (vimhelplint)

- autoload/neomake/makers/ft/python.vim
This was meant to parse the column out of `\s+\^` with compilation
errors from pyflakes, but is not used since pyflakes 0.7.3 anymore [1].
It would trigger different test outcome with Vim patch 8.0.0026 [2].
1: https://github.com/PyCQA/pyflakes/commit/5946f55
2: https://github.com/vim/vim/commit/9b4579481
> python: pyflakes/flake8: errorformat: remove '%-Z%p^'

- autoload/neomake/makers/ft/markdown.vim
- tests/ft_markdown.vader
Some error messages of markdownlint contain also a character. This
caused the character to be interpreted as line and the line to be part
of the filename.
Example:
```
README.md:1:81 MD013/line-length Line length [Expected: 80; Actual: 129]
```
Closes #2480
> Fix errorformat of markdownlint

- autoload/neomake/makers/ft/python.vim
- tests/ft_python.vader
Fixes usage with custom `exe` / `args`.
Ref: https://github.com/neomake/neomake/issues/2107#issuecomment-658018872.
> python: mypy: append `--follow-imports=silent`

- autoload/neomake/makers/ft/clojure.vim
- tests/ft_clojure.vader
- tests/main.vader
I've gotten most of the way there, but I'm having some issues with stdin
support.  It seems that %t is  not being replaced with `-`, but instead
it is the full path to the file.
I had considered just doing
```vim
self.args = ['--filename', '%'] + self.args
```
But that's not done by any other maker, so I thought I should check
first.
Is there a way to do use these two features together that I've missed?
> Add clj-kondo support

- autoload/neomake/makers/ft/dockerfile.vim
Apparently added in https://github.com/hadolint/hadolint/commit/2006e27b2882f929428a7f7f57fc98b100fb0185 (v1.23.0), although probably only later enabled by default.
> dockerfile: hadolint: use `--no-color`

- autoload/neomake/makers/ft/nix.vim
Example error message
error: undefined variable 'bar'
at /tmp/foo.nix:2:1:
1| { foo }:
2| bar
| ^
3|
> makers/nix: adapt error format to nix >= 2.4

- autoload/neomake/makers/ft/ruby.vim
Fixes https://github.com/neomake/neomake/issues/2548.
> ruby: remove `-T1` with ruby maker for ruby3

- autoload/neomake/makers/ft/javascript.vim
Hello!
Sometimes, the _eslint_ maker does not report the line or the column correctly. An example of this is this message when it is misconfigured:
```json
{
"ruleId": null,
"fatal": true,
"severity": 2,
"message": "Parsing error: ESLint was configured to run on `<tsconfigRootDir>/foo.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json\nHowever, that TSConfig does not include this file. Either:\n- Change ESLint's list of included files to not include this file\n- Change that TSConfig to include this file\n- Create a new TSConfig that includes this file and include it in your parserOptions.project\nSee the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does- …
```
> Use default line & column when is not present on eslint maker
